/* The Friendly Robot Travel Agency: the blog, back. Pierce's own excursion posts from the Wishbones & TEE-HEES archive (2025), one per excurience,
   thirteen planet welcomes, and the four taglines that were published. Rick wrote the posts and reviewed them, and kept the two voices apart. */
export const TFRTA = {
 "planets": [
  {
   "slug": "planet-zee",
   "name": "Planet Zee",
   "welcome": "Where everything takes exactly as long as it needs to, plus eternity. Coffee that comes with a lottery system, beauty pageants that never end, and paperwork that follows you into the afterlife.",
   "video": "6c593b_79482a1e700843e08464c50db54f9f70",
   "post": {
    "title": "Slow Tourism",
    "line": "Color arrives when you do. Patience is the native language here."
   }
  },
  {
   "slug": "yaaarghs-revenge",
   "name": "Yaaargh's Revenge",
   "welcome": "Welcome to Yaaargh's Revenge, where piracy got a marketing department. Bootleg games that made more money than the originals, convenience stores that steal from you while you shop, and a landfill full of gaming's worst mistakes. Sometimes crime really does pay.",
   "video": "6c593b_9382c02862e1482e86271f75ff75dc1f",
   "post": {
    "title": "Pirate Ruins",
    "line": "Legendary incompetence, perfect vibes."
   }
  },
  {
   "slug": "oogh-iv",
   "name": "OOGH-IV",
   "welcome": "Welcome to OOGH-IV, where the total vocabulary is 40 words. Counting past ten causes riots, red light districts run on confusion, and the local pharmacy sells enlightenment by way of psychedelic slugs. Sometimes less is definitely more.",
   "video": "6c593b_a53f86e691504629ad75eaa660b3ca0c",
   "post": null
  },
  {
   "slug": "prearth",
   "name": "Prearth",
   "welcome": "Welcome to Prearth, where the end is coming and everyone's dancing to it. Underground clubs that sync their bass drops to asteroid impacts, radio stations that broadcast from the molten core, and poets who rap prophecies no one listens to. If the world's ending, might as well party through it.",
   "video": "6c593b_5e871bafdf5e440e8cfc613ac386f9fd",
   "post": null
  },
  {
   "slug": "that-other-planet",
   "name": "That Other Planet",
   "welcome": "Welcome to That Other Planet, where corporate intellects have mastered the art of being too smart for their own good. Toys that create real galaxies (with real tax bills), game shows that answer every question while helping no one, and networking events that happen across multiple dimensions. Sometimes being the smartest beings in the universe is the dumbest thing you can be.",
   "video": "6c593b_72c26fb141fb4ba9984015abe3d3be14",
   "post": null
  },
  {
   "slug": "figuria",
   "name": "Figuria",
   "welcome": "Planet of action figures and manufactured dreams.\nWhere hope is a scam, but you dig anyway.\n\nToy stores that weaponize nostalgia, adventure parks where the heroes always win (for a price), and factories where dreams get packaged and sold back to their original owners. Sometimes the best adventures are the ones you can afford to lose.",
   "video": "6c593b_abd1be771f7d4c08a5a2b4dcafedbe29",
   "post": null
  },
  {
   "slug": "dens-crevice",
   "name": "Den's Crevice",
   "welcome": "Planet of fire-breathing dragons and questionable decisions.\nWhere intelligence meets gullibility in volcanic harmony.\n\nVolcano spas where relaxation meets third-degree burns, treasure vaults that charge admission to see your own stolen goods, and comedy clubs where the stage literally erupts with every punchline. Sometimes the hottest entertainment leaves permanent scars.",
   "video": "6c593b_8ecfb33454044103813ab1c25ae5e126",
   "post": null
  },
  {
   "slug": "heliumdrum",
   "name": "Heliumdrum",
   "welcome": "Explore the deflating wonders of Heliumdrum.\n\nFloating zoos where the exhibits are slowly deflating, insurance scams involving balloon creatures, and a whole economy built on the promise that this time the balloons won't pop. Sometimes it's better to just let the air out.",
   "video": "6c593b_e794ab14bb95473c81dceb886b8b8754",
   "post": {
    "title": "Weightless City",
    "line": "Float without panic. Floating Zoos drift by."
   }
  },
  {
   "slug": "washy-washy-ii",
   "name": "Washy Washy II",
   "welcome": "Planet of sock puppets and hard-nosed dealings.\nWhere civilization is held together by lint and unresolved trauma.\n\nLaundromats that sort more than just clothes, fashion shows where the models are held together by hope and safety pins, and dry cleaners that specialize in removing existential stains. Sometimes the fabric of reality needs a good wash.",
   "video": "6c593b_1fb04def546547f2a2ddc11c2f66ba3b",
   "post": null
  },
  {
   "slug": "yarnia",
   "name": "Yarnia",
   "welcome": "Planet of hate-filled yarn beings where love is banned.\nThe Lovelace Galaxy's ironic contradiction - where soft materials hide sharp intentions.\n\nKnitting circles that plot world domination one stitch at a time, yarn shops where the products fight back, and craft fairs where creativity comes with a body count. Sometimes the coziest hobbies hide the sharpest intentions.",
   "video": "6c593b_bcde7d0aad1d49e0867808e3b3fe528e",
   "post": null
  },
  {
   "slug": "hungary",
   "name": "Hungary",
   "welcome": "Planet of anthropomorphic food beings with feelings. Where every meal is a moral dilemma and dinner fights back. Restaurants where the menu argues with your order, cooking competitions where ingredients fight for their lives, and all-you-can-eat buffets that eat back. Sometimes the most satisfying meals are the ones that put up a fight.",
   "video": "6c593b_dc809093b8174480bab7761bd4519802",
   "post": null
  },
  {
   "slug": "guffaw-7",
   "name": "Guffaw-7",
   "welcome": "Planet where everyone is a comedian and comedy is combat. Where laughter isn't guaranteed, but public execution absolutely is. Comedy clubs where silence is punishable by death, joke factories that mass-produce depression, and stand-up venues where heckling is a capital offense. Sometimes the funniest comedy comes with the deadliest consequences.",
   "video": "f08d21_e0fe5177066b441baf1a318c823b000a",
   "post": {
    "title": "Silent Comedy Central",
    "line": "Bombing as a love language."
   }
  },
  {
   "slug": "spee-ider-grove",
   "name": "Spee-ider Grove",
   "welcome": "Planet where eight legs, one goal: attention. Think Hollywood, but stickier and more fatal. Talent agencies that literally trap their clients, red carpet events where the carpet is actually a web, and award shows where the only prize is getting out alive. Sometimes fame really is a sticky situation.",
   "video": "f08d21_018e9bfc256044878ac6dcd1b4c96b3a",
   "post": null
  }
 ],
 "posts": [
  {
   "id": "ptu-zee-1",
   "fvId": "ptu-zee-1",
   "slug": "planet-zee",
   "n": 1,
   "title": "Barry, the First Official Sponsor Zombie",
   "headline": "Barry, the First Official Sponsor Zombie",
   "sub": "Brain Bean Coffee where 99 out of 100 customers leave empty-handed",
   "body": "Barry runs Brain Bean Coffee, where 99 out of 100 customers leave empty-handed. He's better at waiting than others and his strategy is to outlast everyone. The rare winners regret their victories immediately. Rick tried to bribe his way ahead but ended up further back with the bribe money gone.",
   "amenities": [
    "Probability-based coffee service",
    "Eternal waiting experience",
    "Lottery system integration",
    "Undead barista expertise",
    "Afterlife networking opportunities",
    "Patience training included"
   ],
   "wishbones": "800 Wishbones",
   "video": "f08d21_5eea9895335c482d9a7162efb42d77ce",
   "thumb": "https://static.wixstatic.com/media/0caac7_31fe8d45cdfb4758ab4322768d0a3741~mv2.png",
   "review": "Time is optional here. Sanity? Less so. I entered as a visitor and left as a philosophical concept. If patience is a virtue, this place is a billion-dollar shrine.",
   "teehees": 4
  },
  {
   "id": "ptu-zee-2",
   "fvId": "ptu-zee-2",
   "slug": "planet-zee",
   "n": 2,
   "title": "Miss Planet Zee Pageant",
   "headline": "Miss Planet Zee Pageant",
   "sub": "An endless pageant of undead beauty queens where survival is key",
   "body": "An endless pageant of undead beauty queens where survival is key. The pageant has been running for millennia with contestants who age, die, become zombies, and keep competing. Rick saw a contestant lose a leg, eat it, and get extra points for resourcefulness.",
   "amenities": [
    "Eternal beauty competition",
    "Undead contestant participation",
    "Survival-based judging",
    "Regenerative talent shows",
    "Afterlife entertainment",
    "Zombification ceremony"
   ],
   "wishbones": "800 Wishbones",
   "video": "f08d21_819f36d5f16647099a869616364a6aba",
   "thumb": "https://static.wixstatic.com/media/0caac7_31fe8d45cdfb4758ab4322768d0a3741~mv2.png",
   "review": "The pageant never ends, which is both its charm and its curse. Watching someone win by eating their own detached limb redefined my understanding of talent competitions.",
   "teehees": 4
  },
  {
   "id": "ptu-zee-3",
   "fvId": "ptu-zee-3",
   "slug": "planet-zee",
   "n": 3,
   "title": "Brain Bean Coffee",
   "headline": "Brain Bean Coffee",
   "sub": "A coffee shop where only 1 in 100 customers gets a drink",
   "body": "Barry's coffee shop - a lottery where only 1 in 100 customers gets a drink. Rick waited for years, saw the previous person get a cup and leave it, and received an empty cup when he reached the counter. The establishment continues thriving on collective optimism and individual disappointment.",
   "amenities": [
    "Lottery-based beverage service",
    "Eternal queue experience",
    "Philosophical waiting lessons",
    "Disappointment management",
    "Undead barista wisdom",
    "Existential coffee education"
   ],
   "wishbones": "800 Wishbones",
   "video": "f08d21_af780b815d6e4168a60ec05866a3cbdb",
   "thumb": "https://static.wixstatic.com/media/0caac7_31fe8d45cdfb4758ab4322768d0a3741~mv2.png",
   "review": "Ordered a medium roast, got a lottery ticket instead. Lost, obviously. Barry just shrugged and said 'next time.' There won't be a next time, Barry.",
   "teehees": 2
  },
  {
   "id": "ptu-yaaargh-1",
   "fvId": "ptu-yaaargh-1",
   "slug": "yaaarghs-revenge",
   "n": 1,
   "title": "The Original Pirated Game",
   "headline": "The Original Pirated Game",
   "sub": "They stole the game, kept the fortune, added two 'a's",
   "body": "Experience the first ever (literally) pirated game! Before The Great Atari Disaster buried their hopes in sand, the Copy Cats of Yaaargh's Revenge pulled off one perfect heist. They didn't just copy Yars' Revenge—they took it outright, slapped on two extra 'a's, and dared anyone to stop them. Play the infamous bootleg in back-alley arcades where the game still runs on questionable machines.",
   "amenities": [
    "Original bootleg arcade access",
    "Pirate gaming history tour",
    "Back-alley arcade experience",
    "Developer notes in pirate slang",
    "Authentic heist memorabilia",
    "Questionable legality thrills"
   ],
   "wishbones": "400 Wishbones",
   "video": "0caac7_acd0e7c03f78462eaa70bdd1c3fb2fa5",
   "thumb": "https://static.wixstatic.com/media/0caac7_0068eb9bb79d47b58730dad2c140acc9~mv2.png",
   "review": "Booted it up expecting a cheap rip-off. Ten hours later, I was still playing. Say what you will about piracy—it's got replay value. The title screen winked at me.",
   "teehees": 4
  },
  {
   "id": "ptu-yaaargh-2",
   "fvId": "ptu-yaaargh-2",
   "slug": "yaaarghs-revenge",
   "n": 2,
   "title": "The Great Atari Disaster",
   "headline": "The Great Atari Disaster",
   "sub": "They dreamed of gold. They got a landfill.",
   "body": "Dig through the legendary landfill where millions of E.T. cartridges were buried after The Great Atari Disaster. The Copy Cats thought they'd outgrown crime, bet everything on E.T., and walked straight into disaster. Now you can hunt for buried cartridges in the digital graveyard where dreams went to decompose.",
   "amenities": [
    "Authentic landfill excavation",
    "Digital graveyard exploration",
    "E.T. cartridge hunting",
    "Disaster history lessons",
    "Buried treasure seeking",
    "Failure archaeology"
   ],
   "wishbones": "250 Wishbones",
   "video": "f08d21_56fd884a2ab24cb2b26fca058df8ebb8",
   "thumb": "https://static.wixstatic.com/media/0caac7_0068eb9bb79d47b58730dad2c140acc9~mv2.png",
   "review": "Spent six hours digging and found exactly what I was looking for—a single, intact E.T. cartridge. Spent six more hours realizing that was never a win. Some things should stay buried.",
   "teehees": 1
  },
  {
   "id": "ptu-yaaargh-3",
   "fvId": "ptu-yaaargh-3",
   "slug": "yaaarghs-revenge",
   "n": 3,
   "title": "Booty for Your Booty",
   "headline": "Booty for Your Booty",
   "sub": "Every deal's a steal. Sometimes literally.",
   "body": "Experience the only fueling station where the gas is optional but the scam is mandatory. The shelves groan under 'limited-edition' loot crates, expired booze marketed as 'aged to perfection,' and mystery bags that promise treasure but deliver regret. The fuel pumps run on an honor system—someone's always siphoning from your tank.",
   "amenities": [
    "Authentic scam experience",
    "Limited-edition loot crates",
    "Mystery bag gambling",
    "Honor system fuel pumps",
    "Expired treasure hunting",
    "Loyalty card schemes"
   ],
   "wishbones": "180 Wishbones",
   "video": "f08d21_dfba6e78fea64f8f9640dbc2002dd5de",
   "thumb": "https://static.wixstatic.com/media/0caac7_0068eb9bb79d47b58730dad2c140acc9~mv2.png",
   "review": "Stopped for a quick refill and a snack. Left with half a tank, a bag of 'authentic pirate doubloons,' and a loyalty card that somehow charges me a monthly fee. Still not sure if I bought gas or just funded their next heist.",
   "teehees": 4
  },
  {
   "id": "ptu-oogh-iv-1",
   "fvId": "ptu-oogh-iv-1",
   "slug": "oogh-iv",
   "n": 1,
   "title": "iCount Launch Event",
   "headline": "iCount Launch Event",
   "sub": "This time, they're aiming for eleven.",
   "body": "The iCount wasn't invented. It was unleashed. A crude abacus—stone beads on a splintered stick—built by a Stoner who didn't know better and backed by a crowd that didn't know worse. They slid a bead. Eleven appeared. Immediate screaming. A fire breaks out—no one knows if it was set on purpose or if fire itself is protesting. Elders argue over whether to destroy the device or build a bigger one.",
   "amenities": [
    "Dangerous counting demonstration",
    "Stone bead abacus operation",
    "Riot participation experience",
    "Mathematical terrorism witness",
    "Number revolution history",
    "Prehistoric panic immersion"
   ],
   "wishbones": "11 Wishbones",
   "video": "f08d21_a13cb966e9c24a5aa47909250316c642",
   "thumb": "https://static.wixstatic.com/media/0caac7_7ce3dd82de904cbc991398fa98ee12b3~mv2.png",
   "review": "They slid a bead. Eleven appeared. The crowd scattered like they'd angered a god. Someone dropped their club and called it 'too dangerous to wield.' Another started praying. By the time I left, the abacus had been outlawed, and so had the concept of 'more.'",
   "teehees": 5
  },
  {
   "id": "ptu-oogh-iv-2",
   "fvId": "ptu-oogh-iv-2",
   "slug": "oogh-iv",
   "n": 2,
   "title": "OOGH-IV Red Light District",
   "headline": "OOGH-IV Red Light District",
   "sub": "They barely understand fire, but somehow, they built this.",
   "body": "Stoners don't fully grasp the concept of a red-light district, but that hasn't stopped them from building one. What started as a barter system gone wildly off the rails has become OOGH-IV's most bafflingly profitable industry. A glowing, chaotic marketplace where nobody's entirely sure what's for sale—but everybody's buying. The longest-running show has been going for three years. No one wants to be the first to blink.",
   "amenities": [
    "Confused entertainment experience",
    "Barter system gone wrong",
    "Endless peep show endurance",
    "Prehistoric adult entertainment",
    "Chaotic marketplace exploration",
    "Poor judgment participation"
   ],
   "wishbones": "40 Wishbones",
   "video": "f08d21_2830d39cb12b44a48ce9f20473c14071",
   "thumb": "https://static.wixstatic.com/media/0caac7_7ce3dd82de904cbc991398fa98ee12b3~mv2.png",
   "review": "Paid for a show. Performer made direct eye contact and just stood there, breathing heavily. Didn't know if it was intimidation or part of the act. After five minutes, I left. He was still there. Pretty sure he won.",
   "teehees": 3
  },
  {
   "id": "ptu-oogh-iv-3",
   "fvId": "ptu-oogh-iv-3",
   "slug": "oogh-iv",
   "n": 3,
   "title": "Brad's \"Pharmacy\"",
   "headline": "Brad's \"Pharmacy\"",
   "sub": "Healing? Maybe. Expansion? Guaranteed.",
   "body": "Brad, the most eloquent Stoner alive, has cracked open the universe—or at least his own mind a few times—and discovered something inside. He speaks in almost full sentences, wears nothing but vibes, and features one thing: slugs. His most famous? The 50/50 Slug. Half the time, it's transcendence. The other half, you wake up three days later in a cave you don't remember entering with objects you refuse to part with.",
   "amenities": [
    "Psychedelic slug experiences",
    "50/50 transcendence probability",
    "Cave awakening adventures",
    "Mysterious object acquisition",
    "Mind expansion therapy",
    "Philosophical detour guidance"
   ],
   "wishbones": "2 Wishbones",
   "video": "f08d21_d491f459a5684ad19322298b6a27c6f8",
   "thumb": "https://static.wixstatic.com/media/0caac7_7ce3dd82de904cbc991398fa98ee12b3~mv2.png",
   "review": "Brad held up two slugs and said, 'One of these is gonna change your life. The other will also change your life, but in a way that makes no sense.' I picked one. Woke up three days later, holding a rock that isn't from this planet. Brad took one look at it and whispered, 'Oh. That's new.'",
   "teehees": 4
  },
  {
   "id": "club-isi",
   "fvId": null,
   "slug": "prearth",
   "n": 1,
   "title": "Club iSi",
   "headline": "Club iSi",
   "sub": "If the world's ending, you might as well dance through it.",
   "body": "Nobody knows who owns Club iSi—or if ownership is even a concept here. It's Prearth's loudest, deepest, most legally ambiguous venue, pulsing at the bottom of a crater nobody remembers forming. The music? Perfect. The floor? Mostly stable. The exit? Theoretical. The only guarantee is that the bassline syncs perfectly with incoming asteroid impacts, a feature that might be intentional but probably isn't.",
   "amenities": [
    "Asteroid-synced bass drops",
    "Underground crater location",
    "Legally ambiguous ownership",
    "VIP booth experiences",
    "Hidden staircase exploration",
    "Apocalyptic dance floors"
   ],
   "wishbones": "750 Wishbones",
   "video": "f08d21_9f05e9511d594da2b56238ae04a7e85e",
   "thumb": "https://static.wixstatic.com/media/0caac7_f25d2e2db6274e1db54eea0579115a9d~mv2.png",
   "review": "Was only supposed to stop in for a drink. Woke up in a VIP booth I did not pay for, wearing sunglasses I did not own, across from a dino who told me I 'owed him big' before disappearing into a hidden staircase I still can't find. The music was incredible, though.",
   "teehees": 4
  },
  {
   "id": "ptu-prearth-2",
   "fvId": "ptu-prearth-2",
   "slug": "prearth",
   "n": 2,
   "title": "PTU-R Headquarters",
   "headline": "PTU-R Headquarters",
   "sub": "If the world's ending, you might as well listen to something good.",
   "body": "Broadcasting straight from Prearth's molten core, PTU-R is the loudest, most reckless radio station in the PTU. The DJs? Unknown. The playlists? Fire. The survival rate? Debatable. It's a sonic lifeline for Aptors too reckless to care that the sky is actively falling. A nonstop mix of news, noise, and apocalyptic basslines, PTU-R doesn't just report on the end—it remixes it.",
   "amenities": [
    "Molten core broadcasting",
    "Unknown DJ experiences",
    "Apocalyptic bassline mixing",
    "Reckless radio programming",
    "End-times news remixing",
    "Sonic lifeline access"
   ],
   "wishbones": "125 Wishbones",
   "video": "f08d21_b327eb573f7a42c6a2daaa6b0e103b9b",
   "thumb": "https://static.wixstatic.com/media/0caac7_f25d2e2db6274e1db54eea0579115a9d~mv2.png",
   "review": "Tried changing the station. The radio refused. Figured it was broken. Turns out, PTU-R doesn't just play music—it picks its listeners. And I wasn't allowed to leave until the song finished. Good thing it slapped.",
   "teehees": 4
  },
  {
   "id": "ptu-prearth-1",
   "fvId": "ptu-prearth-1",
   "slug": "prearth",
   "n": 3,
   "title": "The Velocirapper",
   "headline": "The Velocirapper",
   "sub": "The end is coming. He's already written the soundtrack.",
   "body": "The Velocirapper doesn't run from Prearth's collapse—he narrates it. A lone figure weaving through the wreckage, his flow hits like a meteor, his verses faster than the asteroid that no one's ready for. Every rhyme is a prophecy, every beat a warning—but the Aptors don't listen. They stomp past, nodding like they get it, missing every single clue that their days are numbered.",
   "amenities": [
    "Prophetic rap performances",
    "Apocalyptic verse writing",
    "Meteor-impact flow style",
    "End-times beat warnings",
    "Collapse narration artistry",
    "Final verse experiences"
   ],
   "wishbones": "175 Wishbones",
   "video": "f08d21_c0f911eebcbb47259ab072421946cadd",
   "thumb": "https://static.wixstatic.com/media/0caac7_f25d2e2db6274e1db54eea0579115a9d~mv2.png",
   "review": "He was mid-verse when the first tremor hit. The crowd panicked. He didn't. Just switched his flow to match the quake and kept going. I don't know if that was confidence or resignation, but either way, it was the last show I'll ever forget.",
   "teehees": 5
  },
  {
   "id": "ptu-that-other-planet-1",
   "fvId": "ptu-that-other-planet-1",
   "slug": "that-other-planet",
   "n": 1,
   "title": "The Galax-O-Matic",
   "headline": "The Galax-O-Matic",
   "sub": "Spin the dial, own the stars. Or just the tax bill.",
   "body": "On That Other Planet, the Galax-O-Matic is marketed as a harmless plaything, a fun little gadget that lets children design their own galaxies. But here's the trick—every spin is real. Twist the dial, and somewhere in the PTU, a new star system flares to life. A nebula warps into existence. A black hole decides it's your problem now. And then the bills start rolling in. The Capitols giggle as your 'game' slaps you with intergalactic zoning laws, gravity fees, and a rapidly compounding cosmic debt.",
   "amenities": [
    "Real galaxy creation",
    "Cosmic debt accumulation",
    "Intergalactic tax liabilities",
    "Zoning law violations",
    "Gravity fee assessments",
    "Capitol-designed financial ruin"
   ],
   "wishbones": "800 Wishbones",
   "video": "f08d21_2ab20d3f324d4fc284e78999f44e381b",
   "thumb": "https://static.wixstatic.com/media/0caac7_66b2a4c0705d496c85133c210b3731e6~mv2.png",
   "review": "Created a solar system on my lunch break. Thought it was a simulator. Three weeks later, I got a tax bill from a civilization I accidentally invented. They want me to claim them as dependents. The Capitols are still laughing.",
   "teehees": 3
  },
  {
   "id": "ptu-that-other-planet-2",
   "fvId": "ptu-that-other-planet-2",
   "slug": "that-other-planet",
   "n": 2,
   "title": "We Come in Peace. Sometimes.",
   "headline": "We Come in Peace. Sometimes.",
   "sub": "Every answer spawns three new riddles",
   "body": "This isn't television—it's intellectual warfare broadcast for entertainment. The Capitols host a show where beings from across the PTU submit their most pressing questions, only to receive answers so complex they create new problems. Each episode features rapid-fire responses that technically solve everything while practically helping nothing. The hosts, smug corporate beings with towering intellects, consider confusion a form of education and bewilderment a sign of growth.",
   "amenities": [
    "Intellectual warfare participation",
    "Rapid-fire question demolition",
    "Confusion-based education",
    "Bewilderment growth therapy",
    "Corporate smugness exposure",
    "Live audience humiliation"
   ],
   "wishbones": "350 Wishbones",
   "video": "f08d21_3e16baf5dc9f4b77bc06b728e17ccdc2",
   "thumb": "https://static.wixstatic.com/media/0caac7_66b2a4c0705d496c85133c210b3731e6~mv2.png",
   "review": "Asked a simple question about faster-than-light travel. Got a forty-minute answer about quantum consciousness that somehow made me question if I existed. Felt very educated and completely useless.",
   "teehees": 4
  },
  {
   "id": "ptu-that-other-planet-3",
   "fvId": "ptu-that-other-planet-3",
   "slug": "that-other-planet",
   "n": 3,
   "title": "Probe Events",
   "headline": "Probe Events",
   "sub": "Every conversation happens in parallel timelines",
   "body": "The Corporate Probe Party represents the pinnacle of Capitol networking events, where interdimensional team building meets accidental consciousness expansion. What begins as a standard corporate mixer quickly evolves into an existential crisis with complimentary drinks and mandatory fun. The event space defies conventional architecture—rooms exist in multiple dimensions simultaneously, allowing for conversations that happen in parallel timelines while the bar serves drinks that taste like childhood memories and regret.",
   "amenities": [
    "Interdimensional networking",
    "Parallel timeline conversations",
    "Existential crisis management",
    "Mandatory fun compliance",
    "Memory-flavored beverages",
    "Multi-reality business cards"
   ],
   "wishbones": "600 Wishbones",
   "video": "f08d21_858160b5f5c14a0bb8fe2682ff5f4792",
   "thumb": "https://static.wixstatic.com/media/0caac7_66b2a4c0705d496c85133c210b3731e6~mv2.png",
   "review": "Stepped in for a quick networking session. Blinked and found myself at a different party on a different planet, holding a drink I didn't order, talking to my future self about quarterly projections. The Capitols call this 'efficient socializing.'",
   "teehees": 4
  },
  {
   "id": "ptu-figuria-1",
   "fvId": "ptu-figuria-1",
   "slug": "figuria",
   "n": 1,
   "title": "The Pile",
   "headline": "The Pile",
   "sub": "It's just a junk heap—but keep digging, maybe this time it's different.",
   "body": "Figuria doesn't run on logic. It runs on blind, desperate faith, and nowhere embodies that better than The Pile—a sprawling wasteland of discarded action figure parts, stacked high in the eternal hope that broken things will fix themselves. A graveyard? Maybe. A treasure hoard? If you ask the Go Figures, absolutely. They say that if you dig deep enough, you'll find something whole. They are liars. And yet, you'll dig. Because maybe—just maybe—this time will be different. Maybe this knight's missing a head, but his armor is pristine. Maybe this wizard's robe is intact, even if his legs refuse to stay attached. The search never stops, because the almost is just as intoxicating as the find. And when you inevitably walk away clutching a handful of mismatched plastic limbs like war trophies, you'll tell yourself it was worth it.\n\nThe Friendly Robot Travel Agency recommends packing a strong sense of denial. The Pile never gives. It only takes. And it always, always calls you back.",
   "amenities": [
    "Endless scavenging opportunities",
    "Mismatched part collection",
    "Broken dream archaeology",
    "Junk heap navigation",
    "Hope maintenance services",
    "Denial reinforcement therapy"
   ],
   "wishbones": "80 Wishbones",
   "video": "f08d21_9d044a9db36f4147bee6f5809b8c3638",
   "thumb": "https://static.wixstatic.com/media/0caac7_cb3420598d1c4857adb51336e683a4b7~mv2.png",
   "review": "I found a sword, a crown, and a kingdom in ruin. Kept digging. Found another sword. Of course, I'd go back—because even knowing it's a scam didn't make me stop.",
   "teehees": 2
  },
  {
   "id": "ptu-figuria-2",
   "fvId": "ptu-figuria-2",
   "slug": "figuria",
   "n": 2,
   "title": "The Pop 'N Lock",
   "headline": "The Pop 'N Lock",
   "sub": "No receipts, no guarantees.",
   "body": "It starts with a whisper. A quiet exchange in a backroom lit by dying neon, where Go Figures trade limbs like currency. A hand for a foot. A torso for a dream. The dealers don't ask where your last piece came from, and you don't ask why the one they're handing over is still twitching. The Pop 'N Lock operates on one unshakable rule—if it fits, it's yours. If it doesn't, it's still yours. It's meant to be an upgrade. A clean swap. A second chance at being whole. But sometimes, a piece from The Pile sneaks in. And once it's locked in place, that's you now. Maybe the new leg bends the wrong way. Maybe the new arm won't let go. Maybe the new head has memories that aren't yours. Either way, The Pop 'N Lock doesn't do exchanges. If you walked in looking for an edge, you'd better hope you can live with what you found.\n\nThe Friendly Robot Travel Agency recommends walking in like you belong and leaving before you don't. The only way to win at The Pop 'N Lock is making them believe you did.",
   "amenities": [
    "Limb exchange services",
    "Backroom modification access",
    "Twitching part warranties",
    "Memory transfer risks",
    "No-return policy enforcement",
    "Neon-lit atmosphere"
   ],
   "wishbones": "150 Wishbones",
   "video": "f08d21_7da6a26604de4c3c809f8fa1de39cc41",
   "thumb": "https://static.wixstatic.com/media/0caac7_cb3420598d1c4857adb51336e683a4b7~mv2.png",
   "review": "It felt like an upgrade right up until I tried to run. Now I just move with...character.",
   "teehees": 3
  },
  {
   "id": "ptu-figuria-3",
   "fvId": "ptu-figuria-3",
   "slug": "figuria",
   "n": 3,
   "title": "Alien Plants",
   "headline": "Alien Plants",
   "sub": "Start questioning trees. End questioning everything.",
   "body": "Deep in Figuria, past locked gates and a factory that hums like a heartbeat, the Go Figures grow life that never lived. The Alien Plant is their proudest scam—a jungle of perfect replicas, glistening with dewdrops that never fell, roots that never once had to struggle. Because why fight nature when you can manufacture it? Of course, they had help. The Capitols of That Other Planet cracked the code first—turns out air never needed trees. Photosynthesis was a myth propped up by organic propaganda. Once Figuria caught on, the PTU became their best customer. Now, ships stock their cargo holds with flowers that flicker with impossible colors, shifting their petals to follow music instead of sunlight. They never wilt. They never rot. They never die. They're perfect. So perfect that no one asks the real question—if we never needed plants, what else have we been wrong about?\n\nThe Friendly Robot Travel Agency suggests buying in bulk—because once you realize nature was optional, there's no telling what else you'll stop believing in.",
   "amenities": [
    "Artificial photosynthesis tours",
    "Manufactured nature experiences",
    "Dewdrop-free plant viewing",
    "Organic propaganda debunking",
    "Music-responsive flora",
    "Immortal garden access"
   ],
   "wishbones": "Your faith in nature + 120 Wishbones",
   "video": "f08d21_0fa2c5bde4d245f6811c0d7242a802dd",
   "thumb": "https://static.wixstatic.com/media/0caac7_cb3420598d1c4857adb51336e683a4b7~mv2.png",
   "review": "Spent a fortune on a flower that doesn't grow, in air that doesn't need trees. Turns out ignorance isn't free. Just cheaper.",
   "teehees": 3
  },
  {
   "id": "ptu-dens-crevice-1",
   "fvId": "ptu-dens-crevice-1",
   "slug": "dens-crevice",
   "n": 1,
   "title": "Den's Crevasse",
   "headline": "Den's Crevasse",
   "sub": "Roll the dice on your existence",
   "body": "Some doors take you places. This one rolls the dice on your existence.\n\nAt some point, someone should have shut it down. Den's Crevasse has been swallowing travelers for years, spitting them out somewhere, somewhen, or sometimes not at all. No one knows if it's broken or if this is exactly how it's supposed to work. Ask the Dragoons of Den's Crevice, and you'll get a shrug or a drink, but never an answer. What started as an experiment in probability mechanics became a free-for-all with no user manual. Some step through and come back richer, luckier, exactly where they meant to be. Others? Drop from the sky, flat broke, no idea how long they've been gone. A rare few return different—memories they shouldn't have, scars from things that don't exist, entire lives crammed into a single, bad bet. The running theory? Den's Crevasse doesn't just move people—it rewrites them. The backup theory? It works fine. The real issue is nobody's ever asked politely.\n\nThe Friendly Robot Travel Agency does not offer maps, safety briefings, or explanations for what might happen next. If you want certainty, book a shuttle. If you want adventure, step forward, take a deep breath, and hope you come out on the right side of probability.",
   "amenities": [
    "Probability mechanics testing",
    "Temporal displacement risks",
    "Dimensional shifting opportunities",
    "Memory modification services",
    "Existential dice-rolling",
    "Timeline rewriting potential"
   ],
   "wishbones": "Your current timeline + 350 Wishbones",
   "video": "f08d21_9cbe11d6669d431f9356c2f7226b253f",
   "thumb": "https://static.wixstatic.com/media/0caac7_8314178980cc4a46b4e9170ef629530f~mv2.png",
   "review": "I don't know where I went. I don't know how long I was gone. I do know that when I came back, I had a receipt for a meal I don't remember eating and a note in my pocket that just said 'DON'T.' I should probably listen.",
   "teehees": 4
  },
  {
   "id": "ptu-dens-crevice-2",
   "fvId": "ptu-dens-crevice-2",
   "slug": "dens-crevice",
   "n": 2,
   "title": "Holy Hell That's Hot Spa",
   "headline": "Holy Hell That's Hot Spa",
   "sub": "Lava's the least of your burns",
   "body": "Deep within Den's Crevice lies an experience that redefines the concept of wellness tourism. The Holy Hell That's Hot Spa isn't your typical relaxation destination—it's a spiritual crucible where molten agony meets transcendental bliss, operated by the fire-breathing Dragoons who believe pain is the fastest route to enlightenment.\n\nThe spa's signature treatment involves immersion in naturally heated mineral pools that reach temperatures normally reserved for industrial applications. The Dragoons have turned their volcanic habitat into a wellness empire, convincing visitors that if you can survive their 'therapeutic' lava baths, you'll emerge spiritually renewed. The science is questionable, but the experience is undeniably memorable.\n\nWhat sets this spa apart isn't just the extreme temperatures—it's the philosophy behind it. The Dragoons operate on the principle that comfort is the enemy of growth, and they've built an entire wellness industry around controlled suffering. Their motto, 'No Pain, No Transcendence,' is carved into the volcanic rock above each treatment pool. The facilities themselves are a testament to Dragoon engineering and their unique understanding of hospitality.",
   "amenities": [
    "Lava bath immersion therapy",
    "Therapeutic volcanic suffering",
    "Dragoon-guided enlightenment",
    "Industrial-grade heat treatment",
    "Spiritual pain management",
    "Molten mindfulness sessions"
   ],
   "wishbones": "Your pain tolerance + 800 Wishbones",
   "video": "f08d21_75aaabb8b8de4ff197d39cb65aad71cb",
   "thumb": "https://static.wixstatic.com/media/0caac7_8314178980cc4a46b4e9170ef629530f~mv2.png",
   "review": "Stepped in, felt my soul separate from my body. Before I could scream, a Dragoon handed me a drink and said I'd be fine. Crawled out before my bones turned to soup. The drink was surprisingly good.",
   "teehees": 2
  },
  {
   "id": "ptu-dens-crevice-3",
   "fvId": "ptu-dens-crevice-3",
   "slug": "dens-crevice",
   "n": 3,
   "title": "Komodo Clash",
   "headline": "Komodo Clash",
   "sub": "Fire-breathing lizards vs. slightly smaller lizards",
   "body": "Place your bets. The Dragoons of Den's Crevice arrive every year, towering, fire-breathing, and ready to verbally incinerate their Komodo cousins. And every year, they lose. It's become the PTU's most predictable sporting event, yet somehow the most popular gambling destination. The annual Komodo Clash isn't really a battle—it's a masterclass in overconfidence meeting immovable objects.\n\nThe format is simple: Dragoons challenge their smaller Komodo relatives to contests of strength, intellect, and intimidation. The Komodos respond by doing absolutely nothing. They don't fight back, don't engage, don't even acknowledge the challenges. They just exist. And somehow, this passive resistance breaks the Dragoons every single time. Spectators watch in fascination as towering fire-breathers deliver devastating verbal attacks only to be defeated by a slow blink or a casual tail swish.\n\nThe betting pools have become legendary. Seasoned gamblers know to bet against the obvious favorites. First-time visitors consistently lose their shirts betting on the fire-breathing giants.",
   "amenities": [
    "Fire-breathing entertainment",
    "Weaponized indifference viewing",
    "Psychological warfare analysis",
    "Legendary betting opportunities",
    "Existential crisis spectating",
    "Statistical impossibility documentation"
   ],
   "wishbones": "Your gambling instincts + 600 Wishbones",
   "video": "f08d21_7d8d0d366030436e859a741eaac93ac8",
   "thumb": "https://static.wixstatic.com/media/0caac7_8314178980cc4a46b4e9170ef629530f~mv2.png",
   "review": "Put every Wishbone I had on the Dragoons. Easy money, I thought. Watched a dragon deliver a verbal nuke that should have ended the match. The Komodo blinked, maybe. Five minutes later, the dragon was spiraling into an existential crisis, the Komodo was undefeated, and I was flat broke.",
   "teehees": 4
  },
  {
   "id": "ptu-heliumdrum-1",
   "fvId": "ptu-heliumdrum-1",
   "slug": "heliumdrum",
   "n": 1,
   "title": "Private Floating Zoos",
   "headline": "Private Floating Zoos",
   "sub": "A breathtaking spectacle, if you ignore the slow, inevitable decline",
   "body": "Once a marvel of engineering and indulgence, the TFRTA's Private Floating Zoos were built to house the rarest balloon creatures in the PTU—majestic, weightless, and practically immortal. That was the pitch. The reality? Helium runs out. Some of the exhibits are fine—graceful balloon elephants drift in carefully pressurized domes, still inflated, still impressive. Others? Leaking, stretching, sagging into unnatural shapes their original designers never intended.",
   "amenities": [
    "Deflating creature observation",
    "Pressurized dome tours",
    "Balloon animal archaeology",
    "Helium leak documentation",
    "Sagging spectacle viewing",
    "Engineering marvel decay"
   ],
   "wishbones": "Your sense of wonder + 60 Wishbones",
   "video": "f08d21_8c35cdc282214e51b017c2361b9c32af",
   "thumb": "https://static.wixstatic.com/media/0caac7_e46df7216ab54baf8b0e3b7e6808b4e8~mv2.png",
   "review": "Watched a balloon lion floating perfectly still. Guide said it was 'preserved for historical accuracy.' Two minutes later, it let out the weakest, saddest wheeze I've ever heard and deflated mid-air. Guide didn't even blink. Just marked it off a list and kept walking.",
   "teehees": 2
  },
  {
   "id": "ptu-heliumdrum-2",
   "fvId": "ptu-heliumdrum-2",
   "slug": "heliumdrum",
   "n": 2,
   "title": "Repopulation Effort",
   "headline": "Repopulation Effort",
   "sub": "Hope inflates, Pricks deflate, repeat",
   "body": "Scientists developed the Repopulation Machine—a high-tech marvel that breathes new life into Poppies at a premium price. Customers select a species, watch it reinflate before their eyes, and, for a fleeting moment, believe in progress. Then, the Pricks step in. Nobody knows who funds them, where they came from, or how they keep getting away with it.",
   "amenities": [
    "Balloon creature resurrection",
    "Premium reinflation services",
    "Progress illusion therapy",
    "Professional deflation viewing",
    "Hope cycle participation",
    "System failure appreciation"
   ],
   "wishbones": "Your hope for the future + 400 Wishbones",
   "video": "f08d21_b60508552fdd4a92942661c5c30c9407",
   "thumb": "https://static.wixstatic.com/media/0caac7_e46df7216ab54baf8b0e3b7e6808b4e8~mv2.png",
   "review": "Paid a fortune to repopulate a balloon giraffe. Watched it reinflate, get a name, and take its first official bounce into existence. Eighteen seconds later, a Prick appeared out of nowhere and popped it mid-stride. Scientist didn't even flinch.",
   "teehees": 1
  },
  {
   "id": "ptu-heliumdrum-3",
   "fvId": "ptu-heliumdrum-3",
   "slug": "heliumdrum",
   "n": 3,
   "title": "Re-Purposing Factory",
   "headline": "Re-Purposing Factory",
   "sub": "New life, same air, zero dignity",
   "body": "Deflated Poppies are gathered, sorted, and reworked into whatever the market demands. Some are repurposed into cheap party balloons, their past lives as beloved creatures quietly erased. Others become novelty inflatables, parade decorations, 'limited-edition' collectible blimps—anything that can hold its shape just long enough to turn a profit.",
   "amenities": [
    "Deflated creature collection",
    "Dignity removal processes",
    "Past life erasure services",
    "Market-driven recycling",
    "Novelty transformation tours",
    "Profit-maximizing reuse"
   ],
   "wishbones": "Your childhood memories + 75 Wishbones",
   "video": "f08d21_f0a4050722a345d0b4c33bd8b27491ba",
   "thumb": "https://static.wixstatic.com/media/0caac7_e46df7216ab54baf8b0e3b7e6808b4e8~mv2.png",
   "review": "Saw a birthday balloon floating outside the factory, swore I recognized the pattern. Bought one just like it as a kid. Checked the tag—manufactured last week. Mentioned it to a worker. He just patted my shoulder and directed me to the register.",
   "teehees": 2
  },
  {
   "id": "ptu-washy-washy-ii-1",
   "fvId": "ptu-washy-washy-ii-1",
   "slug": "washy-washy-ii",
   "n": 1,
   "title": "Underground Sock Puppet Fight Club",
   "headline": "Underground Sock Puppet Fight Club",
   "sub": "Stitch tight, swing hard, and pray your seams hold",
   "body": "Nobody whispers about Underground Sock Puppet Fight Club—they scream about it, bet on it, and argue over which legendary brawler had the strongest grip or the most devastating right hook. There are no secrets here. If you lose, everyone knows. Your name gets stitched into the Wall of Regret, a patchwork memorial of former champions who once ruled the ring but eventually popped a seam too many. Some retire gracefully. Most don't. The unlucky ones? They don't just lose their fights—they lose their place in the drawer. A Stringer that can't hold its own in battle isn't worth wearing, and on Washy Washy II, that's as good as an eviction notice. A life of luxury? Gone. Replaced by a fate worse than unraveling: permanent status as a cleaning rag.\n\nThe Friendly Robot Travel Agency does not recommend getting too attached to your favorite fighter—because when they go down, they're not coming back up. Place your bets, watch your step, and for the love of fabric, keep your stitches tight.",
   "amenities": [
    "Wall of Regret viewing",
    "Legendary brawler spectating",
    "Seam-popping entertainment",
    "Cleaning rag transformation tours",
    "High-stakes fabric betting",
    "Textile combat training"
   ],
   "wishbones": "250 Wishbones + whatever's in your pockets",
   "video": "f08d21_f2ac03379562412f9eb78909579ac893",
   "thumb": "https://static.wixstatic.com/media/0caac7_3dfd1ea25d8748c0aa82c17ea7838378~mv2.png",
   "review": "Witnessed a Champion Stringer with a mean jab get turned into a dust rag mid-swing—some drunk puppet bumped me, and I nearly bet my boots on a loser with one eye. This place has got a knack for chaos that sticks—left with lint in my lungs and a grin.",
   "teehees": 4
  },
  {
   "id": "ptu-washy-washy-ii-2",
   "fvId": "ptu-washy-washy-ii-2",
   "slug": "washy-washy-ii",
   "n": 2,
   "title": "Sock Market Crash",
   "headline": "Sock Market Crash",
   "sub": "Insider trading meets fabric softener",
   "body": "It was supposed to be a sure thing. The Sock Market ran on high-thread-count speculation, premium brand hype, and a laundering scheme so convoluted even the scammers lost track. Puppets invested big, betting their fortunes on reinforced stitching, vintage elastic, and the ever-elusive Perfect Pair. Then, everything unraveled. Prices tanked. Confidence shriveled faster than a wool sock in a high-heat dryer. Investors who once flexed limited-edition, never-worn-before collections were suddenly begging for singles in back alleys. Meanwhile, the smart ones? They dumped their inventory right before the crash, cashed out, and left the amateurs holding the lint. Now, the market limps along, run by optimists, scammers, and puppets too stubborn to admit their portfolios are just holes waiting to happen.\n\nThe Friendly Robot Travel Agency suggests keeping your socks on your feet and your Wishbones in your pocket. If someone promises you a high-yield return on a rare import, check the seams. If it was such a great investment, they wouldn't be selling.",
   "amenities": [
    "Perfect Pair mythology tours",
    "Market crash observation",
    "Vintage elastic speculation",
    "Laundering scheme education",
    "Back-alley sock trading",
    "Portfolio hole inspection"
   ],
   "wishbones": "Your retirement fund + 75 Wishbones",
   "video": "f08d21_f7130277062a4731a56fa76b8f6cb016",
   "thumb": "https://static.wixstatic.com/media/0caac7_3dfd1ea25d8748c0aa82c17ea7838378~mv2.png",
   "review": "Tried my luck on a high-thread-count investment. Was promised 'immediate returns.' Ended up with a single sock and a long, exhausting speech about market corrections. The real kicker? The guy who sold it to me was wearing my other sock.",
   "teehees": 2
  },
  {
   "id": "ptu-washy-washy-ii-3",
   "fvId": "ptu-washy-washy-ii-3",
   "slug": "washy-washy-ii",
   "n": 3,
   "title": "LASIK Eye Surgery",
   "headline": "LASIK Eye Surgery",
   "sub": "A procedure resulting in permanently affixed googly eyes",
   "body": "They promise perfect vision. They deliver googly eyes that never stop moving. The procedure is performed by sock puppet surgeons who learned medicine from instructional videos that may or may not have been accurate. The googly eyes are industrial-grade and designed to last forever, which is both a selling point and a warning. Patients report improved peripheral vision but note that reading becomes impossible and poker becomes very easy to lose. The constant movement of the eyes creates a hypnotic effect that some find soothing and others find maddening.\n\nThe surgical staff maintains that this is an upgrade, not a side effect. They point to satisfied customers who have adapted to their new visual reality and developed unique coping strategies. The waiting room is full of testimonials from people who claim their googly eyes have improved their lives in unexpected ways.\n\nThe Friendly Robot Travel Agency suggests getting a second opinion from a non-sock-puppet medical professional. If you proceed with the surgery, we recommend avoiding high-stakes gambling, professional driving, and any activity that requires maintaining eye contact.",
   "amenities": [
    "Googly eye installation",
    "Sock puppet surgery experience",
    "Peripheral vision enhancement",
    "Poker disadvantage training",
    "Eye contact elimination therapy",
    "Hypnotic vision effects"
   ],
   "wishbones": "Your ability to make eye contact + 700 Wishbones",
   "video": "f08d21_7954d999244e48008074e576a54a293c",
   "thumb": "https://static.wixstatic.com/media/0caac7_3dfd1ea25d8748c0aa82c17ea7838378~mv2.png",
   "review": "Saw a guy get them and then lose at poker because his eyes twitched. The constant movement gave away every bluff, but he claimed the enhanced peripheral vision helped him spot cheaters. It's like watching someone adapt to a permanent disadvantage by finding creative advantages.",
   "teehees": 1
  },
  {
   "id": "ptu-yarnia-1",
   "fvId": "ptu-yarnia-1",
   "slug": "yarnia",
   "n": 1,
   "title": "The Stitcher",
   "headline": "The Stitcher",
   "sub": "It was meant to heal. It prefers to harvest.",
   "body": "Beneath Yarnia's Hall of Crafting, past the spools of tradition and the looms of legacy, The Stitcher waits. It was meant to be a miracle—sewing warriors back together mid-battle, threading wounds shut before the body had time to protest. But something in the design snagged. It stopped distinguishing between flesh and fabric, between a soldier in need and material to be used. The last person who tested it became inventory. A perfect spool, wound tight, labeled with his own name. No one turns it on. Not anymore. The last scientist who tried spent three days convincing himself his hands hadn't itched to touch the needle. The Stitcher does not call. It does not move. It simply waits. Because someday, someone will sit down. And it will finish the job.\n\nThe Friendly Robot Travel Agency offers front-row seats to the quiet horror. Just don't touch it. Or do. We'll make sure your thread is labeled.",
   "amenities": [
    "Quiet horror observation",
    "Medical nightmare tours",
    "Thread inventory viewing",
    "Healing technology gone wrong",
    "Flesh-to-fabric conversion",
    "Silent machine appreciation"
   ],
   "wishbones": "Free (but you pay with something else)",
   "video": "6c593b_a84ab4466ec345e0925df34183169b1a",
   "thumb": "https://static.wixstatic.com/media/0caac7_df8af5a6869a463f97fa78f471b20df7~mv2.png",
   "review": "Watched it hum, saw the needle twitch, and left before it could take an interest. If I ever sit down, at least make something wearable.",
   "teehees": 1
  },
  {
   "id": "ptu-yarnia-2",
   "fvId": "ptu-yarnia-2",
   "slug": "yarnia",
   "n": 2,
   "title": "The Kumite of Yarnia",
   "headline": "The Kumite of Yarnia",
   "sub": "Soft doesn't mean safe",
   "body": "The Kumite of Yarnia isn't just a fight—it's a reckoning, played out in a ring stitched from centuries of bad blood and worse decisions. The combatants? Thread-bound warriors, crochet brutes, and stuffed champions with nothing to lose but their stuffing. The rules? None. The stakes? Everything. Fights start with a bow and end when someone's seam pops, stuffing spills, or an opponent gets reduced to a pile of tangled yarn. Some Stringer warriors enter with finely reinforced stitches, triple-knotted for endurance. Others rely on the ancient, dishonorable art of unpicking an opponent mid-swing. And then there are the ones who don't fight at all, just standing there, letting the tension build until someone snaps—literally. The crowd? Ruthless. The referees? Absent. The moment the bell rings, it's every soft soul for itself.\n\nThe Friendly Robot Travel Agency advises all visitors to choose their seating wisely—ringside seats come with the real risk of getting hit with stray stuffing. Betting is encouraged, but don't gamble on a fighter with loose ends. Those never last long.",
   "amenities": [
    "Thread-bound warrior combat",
    "Stuffing-spill spectating",
    "Reinforced stitch appreciation",
    "Unpicking technique observation",
    "Seam-popping entertainment",
    "Textile warfare betting"
   ],
   "wishbones": "200 Wishbones (+ medical insurance recommended)",
   "video": "f08d21_636790b9d7f3427aa691b0862af15c57",
   "thumb": "https://static.wixstatic.com/media/0caac7_df8af5a6869a463f97fa78f471b20df7~mv2.png",
   "review": "Bet big on a Stringer with reinforced seams. Watched them get unraveled in two moves by an opponent with a crochet hook and bad intentions. The fight lasted less than a minute. My regret? Still going.",
   "teehees": 4
  },
  {
   "id": "ptu-yarnia-3",
   "fvId": "ptu-yarnia-3",
   "slug": "yarnia",
   "n": 3,
   "title": "Voodoo Doo Doo Doll Workshop",
   "headline": "Voodoo Doo Doo Doll Workshop",
   "sub": "Handmade revenge, now in travel size",
   "body": "On Yarnia, pettiness isn't just a feeling—it's a fine craft passed down through generations. The Voodoo Doo Doo Doll Workshop is where grudges go to be measured, stuffed, and expertly cursed. Pick a doll, customize it with realistic flaws, whisper a name, and let the universe handle the rest. Some hexes are mild, but others? Let's just say the shop has a strict 'no refunds, no evidence, no questions' policy. The Yarnians excel at hate. Their voodoo dolls are masterpieces of malice. Each stitch is a curse. Each button is a bad day. The dolls work. That's the problem. They make custom orders. They already started yours.\n\nThe Friendly Robot Travel Agency suggests using a light touch—unless you'd like to spend the rest of your life checking over your shoulder for your own stitching. Thread carefully.",
   "amenities": [
    "Grudge measurement services",
    "Expert curse application",
    "Masterpiece malice creation",
    "Custom revenge dolls",
    "Pettiness crafting lessons",
    "Hate-based art appreciation"
   ],
   "wishbones": "666 Wishbones (cursed pricing)",
   "video": "f08d21_c8f7f664a2e54b16a10b68b27bc29ae7",
   "thumb": "https://static.wixstatic.com/media/0caac7_df8af5a6869a463f97fa78f471b20df7~mv2.png",
   "review": "Tried to buy a doll, but the shopkeeper took one look at me, sighed, and handed me one that was already finished. Same hair, same clothes, same slightly slouched posture. 'This one's yours,' they said. Didn't even charge me. Just patted me on the back like I should start preparing for something. Haven't slept well since.",
   "teehees": 2
  },
  {
   "id": "ptu-hungary-1",
   "fvId": "ptu-hungary-1",
   "slug": "hungary",
   "n": 1,
   "title": "High-Stakes Food Fights",
   "headline": "High-Stakes Food Fights",
   "sub": "When appetizers attack",
   "body": "Welcome to Hungary's most volatile dining experience, where every meal is a battlefield and every bite could be your last peaceful moment. High-Stakes Food Fights aren't just dinner theater—they're full-contact culinary warfare where the Foodfolk themselves become both the entertainment and the ammunition. The concept is deceptively simple: sentient food beings engage in epic battles while you dine, creating a multi-sensory experience that's part gladiator arena, part restaurant, part existential crisis. The Hungarians have perfected the art of making you question whether you should be eating or fleeing as anthropomorphic vegetables launch themselves at each other with the fury of beings who know their expiration date is approaching.",
   "amenities": [
    "Full-contact culinary warfare",
    "Sentient food gladiator arena",
    "Multi-sensory dining experience",
    "Existential crisis included",
    "Anthropomorphic entertainment",
    "Expiration date drama"
   ],
   "wishbones": "950 Wishbones",
   "video": "f08d21_06f12f4c09bc420b99e79e55cc8a4370",
   "thumb": "https://static.wixstatic.com/media/0caac7_aec854005a38493f96e12d128c331a04~mv2.png",
   "review": "I watched a friendly appetizer become a gladiator in real time. One minute I was admiring the presentation, the next I was watching it dive-bomb a soup course with the intensity of someone who had nothing left to lose. By dessert, I wasn't sure if I was dining or attending a funeral for food.",
   "teehees": 4
  },
  {
   "id": "ptu-hungary-2",
   "fvId": "ptu-hungary-2",
   "slug": "hungary",
   "n": 2,
   "title": "Cornucopia Mandela Museum",
   "headline": "Cornucopia Mandela Museum",
   "sub": "A feast of lies, a banquet of nothing",
   "body": "Some museums preserve history. This one rewrites it. The Cornucopia Mandela Museum claims every famous meal in history was actually sentient foodfolk. The Last Supper? A peace negotiation. Marie Antoinette's cake? A political prisoner. The exhibits change when you're not looking. That sandwich you remember from childhood? It remembers you too. The museum showcases iconic meals that may never have existed, creating false memories so convincing that visitors leave questioning everything they thought they knew about food history. The most disturbing exhibit is the Hall of Empty Plates, where visitors stare at barren dishware while audio recordings describe elaborate meals that were 'too important to actually exist.'",
   "amenities": [
    "History rewriting experience",
    "Sentient meal mythology",
    "False memory creation",
    "Existential food questioning",
    "Hall of Empty Plates",
    "Reality distortion included"
   ],
   "wishbones": "250 Wishbones",
   "video": "f08d21_1153432992dd4f648777cc010d9a1d20",
   "thumb": "https://static.wixstatic.com/media/0caac7_aec854005a38493f96e12d128c331a04~mv2.png",
   "review": "Questioned reality after seeing an empty plate exhibit. Walked in expecting history. Walked out questioning everything. Saw an exhibit on the 'most famous meal in PTU history'—a single empty plate under a spotlight. The placard said it was 'too significant to have happened.' I stared at it for twenty minutes trying to understand what I was missing.",
   "teehees": 4
  },
  {
   "id": "ptu-hungary-3",
   "fvId": "ptu-hungary-3",
   "slug": "hungary",
   "n": 3,
   "title": "Expiration Date",
   "headline": "Expiration Date",
   "sub": "Love's a limited shelf life",
   "body": "They say love is timeless. On Hungary, love is a gamble against rot. There's no compatibility quiz, no carefully curated matches—just a blind date and the quiet hope that your partner isn't actively spoiling. Go on an Expiration Date is Hungary's most beloved, feared, and wildly unpredictable tradition, where travelers are paired with sentient foodfolk whose lifespans range from 'fine wine' to 'last week's seafood special.' Some matches are perfectly aged, deepening in flavor and complexity over the course of an evening. Others turn rancid in real time. Mid-conversation, a date might soften, collapse, or start leaking brine. Chemistry is irrelevant when one of you is ripening faster than the other.",
   "amenities": [
    "Blind date with sentient food",
    "Expiration timeline gambling",
    "Real-time decay romance",
    "Shelf-life compatibility",
    "Disposal fees included",
    "Aging wine possibilities"
   ],
   "wishbones": "600 Wishbones",
   "video": "f08d21_c85fbdb8d53e4900a500ad67651656fd",
   "thumb": "https://static.wixstatic.com/media/0caac7_aec854005a38493f96e12d128c331a04~mv2.png",
   "review": "My date went silent after checking their reflection and was then removed by the waiter. It's not rejection when your date literally can't continue existing. The relationship lasted fifteen minutes, which is apparently above average for Hungary dating.",
   "teehees": 2
  },
  {
   "id": "ptu-guffaw-7-1",
   "fvId": "ptu-guffaw-7-1",
   "slug": "guffaw-7",
   "n": 1,
   "title": "The Gurgle",
   "headline": "The Gurgle",
   "sub": "Gags on tap - drink up, choke on the punchline",
   "body": "On Guffaw-7, bars don't just serve drinks. They serve humiliation. The Gurgle is no exception—weak drinks, strong roasts, and bartenders who have never once let a bad order slide. Try to sip in peace, and someone will make sure you're part of the act. Every barstool is a spotlight. Every patron is waiting for someone to slip. The regulars? Hardened, unshaken, immune to even the meanest punchlines. Newcomers? They rarely make it through a full drink without becoming the freshest material on the menu. One wrong gulp, one laugh at the wrong time, and suddenly, you're the set.",
   "amenities": [
    "Weak drinks, strong roasts",
    "Every barstool is a spotlight",
    "Hardened regular clientele",
    "Freshest material sourcing",
    "Humiliation service included",
    "Therapy not included"
   ],
   "wishbones": "350 Wishbones",
   "video": "f08d21_a7f7137242504e51a099007ffed0eb9d",
   "thumb": "https://static.wixstatic.com/media/0caac7_0d45f1d2a6434b5aa29fdfa359f8aa04~mv2.png",
   "review": "Ordered a drink. Got insulted before I even touched it. Took a sip, got roasted for how I held the glass. Laughed so hard I choked, which only made it worse. Spilled half my drink from shaking, spilled the other half from being called out for it. 10/10 experience, but my self-esteem needs a minute.",
   "teehees": 3
  },
  {
   "id": "ptu-guffaw-7-2",
   "fvId": "ptu-guffaw-7-2",
   "slug": "guffaw-7",
   "n": 2,
   "title": "Comedy Peepshow",
   "headline": "Comedy Peepshow",
   "sub": "Peek 'til you're the punchline",
   "body": "Drop a Wishbone, lift the curtain, and watch the set unfold. The Comedium works the tiny stage, cracking jokes, selling the moment, searching for the one laugh that matters. Yours. Because the second you let one slip—the second you betray yourself with an uncontrolled cackle—everything flips. The stage drops. The curtain slams shut. You're sitting on the stool now. The mic is on. The crowd is waiting. And the comic you were just watching? Front row, sipping a drink, watching you bomb. Pay to watch a comedian, but one laugh makes you the next performer bombing on stage.",
   "amenities": [
    "Watch but don't laugh challenge",
    "Instant role reversal system",
    "Front row heckler guarantee",
    "Bombing footage included",
    "Humiliation guaranteed",
    "Dignity sold separately"
   ],
   "wishbones": "200 Wishbones",
   "video": "f08d21_3f4f2c16e0b145b3995edba6916e324f",
   "thumb": "https://static.wixstatic.com/media/0caac7_0d45f1d2a6434b5aa29fdfa359f8aa04~mv2.png",
   "review": "Paid to watch a set. Laughed once. Next thing I knew, I was holding the mic and regretting everything. The hecklers smelled blood. The comic I was watching? Front row, sipping my dignity like a well-earned drink. No memory of what I said, but the footage says I tried. And failed. Twice.",
   "teehees": 4
  },
  {
   "id": "ptu-guffaw-7-3",
   "fvId": "ptu-guffaw-7-3",
   "slug": "guffaw-7",
   "n": 3,
   "title": "Farm League Comedy Club",
   "headline": "Farm League Comedy Club",
   "sub": "Where bombs build legends",
   "body": "The Farm League Comedy Club isn't just a venue. It's a battlefield where punchlines land, careers don't, and the AI-controlled laugh track hasn't been amused in years. Comediums step into the lights armed with nothing but delusion and a loose five, staring into a crowd that's already circling like sharks. Bombing isn't just an option—it's a certainty. The only question is whether it'll be a quick death or a slow, painful one. The moment a joke misses, the hecklers move in. The AI scoffs. The front row leans forward, sensing blood. Some fight back. Some double down. Some simply disappear, their dignity left behind in the spotlight.",
   "amenities": [
    "AI-controlled laugh track",
    "Shark-like audience behavior",
    "Professional heckler services",
    "Dignity disposal system",
    "Bombing guarantee included",
    "Silence included in price"
   ],
   "wishbones": "150 Wishbones",
   "video": "f08d21_6e5c3d6b66044f71824c1dda4c881289",
   "thumb": "https://static.wixstatic.com/media/0caac7_0d45f1d2a6434b5aa29fdfa359f8aa04~mv2.png",
   "review": "Watched a guy bomb so hard the crowd started laughing at him, so he doubled down and somehow made it worse. By the end, the hecklers were doing a tighter five than he was. Meanwhile, another Comedium got a standing ovation just for walking off early. I think I learned something, but I have no idea what.",
   "teehees": 2
  },
  {
   "id": "ptu-spee-ider-grove-1",
   "fvId": "ptu-spee-ider-grove-1",
   "slug": "spee-ider-grove",
   "n": 1,
   "title": "Web Experts (Tiko Techs)",
   "headline": "Web Experts (Tiko Techs)",
   "sub": "The web works best when you're already stuck",
   "body": "The Tikatikatikos of Spee-ider Grove have perfected speed without substance. They don't just sell networks—they spin them, promising seamless connection with the confidence of creatures that know how to vanish when things fall apart. Every launch is a spectacle, dazzling crowds with cutting-edge demos that last just long enough to get through the presentation. The coverage? Unmatched—until you need it. The contracts? Longer than their service life. The Tiko Techs promise the fastest web in the universe. They deliver—for about three minutes. Then it collapses. They blame your device, your location, your existence.",
   "amenities": [
    "Speed without substance",
    "Cutting-edge demo spectacles",
    "Three-minute network lifespan",
    "Vanishing customer service",
    "Cancellation impossible",
    "Eight-leg technical support"
   ],
   "wishbones": "800 Wishbones per month",
   "video": "0caac7_774ec4df5daf45d39b4132ce6e3feb59",
   "thumb": "https://static.wixstatic.com/media/0caac7_5ee451e97e0a4575aac5e4db230d8649~mv2.png",
   "review": "They guaranteed the fastest service in the PTU. They were right. It disappeared before I could even test it. Called support—got transferred so many times I swear the rep was just running laps around the call center. Now I have three accounts. None of them work.",
   "teehees": 1
  },
  {
   "id": "ptu-spee-ider-grove-2",
   "fvId": "ptu-spee-ider-grove-2",
   "slug": "spee-ider-grove",
   "n": 2,
   "title": "Gargantuan Tarantulas with Spatulas",
   "headline": "Gargantuan Tarantulas with Spatulas",
   "sub": "Chaos in the kitchen",
   "body": "Mornings on Spee-ider Grove aren't peaceful—they're a culinary gauntlet, and Gargantuan Tarantulas with Spatulas is the main event. Breakfast isn't plated—it's launched. The host, an eight-legged whirlwind of confidence and poor impulse control, treats cooking like a high-stakes performance piece, where every flip, toss, and stir comes with a real risk of injury. The only cooking show where survival is part of the recipe. One moment, you're watching a pancake get flipped. The next, it's gone—launched into another dimension. Chef doesn't even blink, just nods and says 'Perfect arc.'",
   "amenities": [
    "High-stakes culinary performance",
    "Eight-legged chef entertainment",
    "Dimensional cooking techniques",
    "Protective gear extra",
    "Survival experience included",
    "Washable clothing recommended"
   ],
   "wishbones": "200 Wishbones",
   "video": "f08d21_567ee09d350b4f94ab4677be1eaaf937",
   "thumb": "https://static.wixstatic.com/media/0caac7_5ee451e97e0a4575aac5e4db230d8649~mv2.png",
   "review": "One moment, I was watching a pancake get flipped. The next, it was gone—launched into another dimension. Chef didn't even blink. Just nodded and said, 'Perfect arc.' I don't know what I ate instead, but it had the consistency of regret.",
   "teehees": 3
  },
  {
   "id": "ptu-spee-ider-grove-3",
   "fvId": "ptu-spee-ider-grove-3",
   "slug": "spee-ider-grove",
   "n": 3,
   "title": "Spee-ider Women Eat Spee-ider Men",
   "headline": "Spee-ider Women Eat Spee-ider Men",
   "sub": "A romantic dinner date (for one)",
   "body": "The Tikatikatikas don't do romance. They do performances—brief, dazzling, and nutritionally necessary. Every night, beneath the silk-draped skyline of Spee-ider Grove, their suitors step into the web, puffed up with delusion and pheromones, spinning empty promises into something that, if you squint, almost looks like hope. The dance is always beautiful. The ending is always the same. One misstep, one quiver of doubt, and she strikes—legs like lightning, fangs like knives, suitor like a snack that should've known better. The crowd erupts. The web trembles. The leftovers sway in the humid air, a grisly testament to overconfidence.",
   "amenities": [
    "Brief, dazzling performances",
    "Nutritionally necessary romance",
    "Silk-draped venue experience",
    "Ponchos available on request",
    "Life insurance recommended",
    "0.03% survival rate"
   ],
   "wishbones": "400 Wishbones",
   "video": "0caac7_eb8bab89693741c48da17357f7978d03",
   "thumb": "https://static.wixstatic.com/media/0caac7_5ee451e97e0a4575aac5e4db230d8649~mv2.png",
   "review": "Watched one strut in like he had a plan. He did not have a plan. I'm still picking webbing out of my shoes. The whole thing was mesmerizing—a ritual this old, this inevitable, played out on silk and leaving nothing behind but scraps.",
   "teehees": 5
  }
 ]
};
