/* DEAD ENDS: what each being says about its own maze. Same voices as OVER THE BOARD (chess/lines.js), fewer occasions.
   greet   you open its maze            start   your first move
   hint    you press Hint                solve   you press Solve (it walks you out; that does not count as an escape)
   slow    forty-five seconds in, still inside   win   you get out
   fast    you get out under its own time        locked  you tap a being whose maze is not open yet
   next    you pick the next planet from the win card */

export const MAZE_LINES = {
  'planet-zee': {
    greet: ['My maze. Everyone in it is waiting for something. You are waiting for the exit.', 'Welcome. The way out exists. I have seen it, once, around 1987.', 'Sit, or walk. The walls do not care which.'],
    start: ['Moving. Noted. Most people stand there a while first.', 'There you go. One step. The queue begins.', 'And so it starts. Slowly, I hope.'],
    hint: ['A hint. I will mark it on your file. The file is long.', 'Half the way, shown. The other half you owe me.', 'Fine. The red line. Do not get used to red lines here.'],
    solve: ['I will walk you out. It does not count. Nothing here counts.', 'Solved, by me. Your name stays off the record.', 'There. The whole way. Watch, and feel nothing.'],
    slow: ['Still in there. Good. Most of my guests never leave.', 'Forty-five seconds. On Planet Zee that is a blink.', 'Take your time. I have taken all of mine.'],
    win: ['Out. Stamped, dated, filed. Next.', 'You escaped. It happens. Rarely. Mark the date.', 'The exit was real after all. I was beginning to wonder.'],
    fast: ['Faster than me. I will have to redo the paperwork.', 'Under my time. I did mine in 1987 and it took a decade.', 'Brisk. Almost rude. Noted with something like respect.'],
    locked: ['Not yet. Get out of mine first.', 'That maze is closed. This one is open. Unfortunately for you.', 'Patience. The line moves one planet at a time.'],
    next: ['Go on, then. The next one is faster. They all are.', 'Off you go. Tell the next being I said nothing.'],
  },
  'yaaarghs-revenge': {
    greet: ["Me maze. Copied from a better one. Ye'll never tell.", 'Welcome aboard. The way out is the way in, flipped. Probably.', "Sit tight. I stole this layout fair and square."],
    start: ["There ye go. I'll be copying that route.", 'Movin. Good. Mind the walls, I did not build them.', 'First step. Mine was the same, years ago, on somebody else\'s map.'],
    hint: ["A hint? That's cheatin. I approve.", 'Half the route, shown. I would have charged for that.', 'Fine, a hint. I copied it from the answer key.'],
    solve: ["I'll walk ye out. Ye owe me a ship.", 'Solved. By me. The credit stays aboard.', 'There. The whole route. Memorize it, like I did.'],
    slow: ['Still in there? I would have copied a way out by now.', 'Forty-five seconds. The crew is laughin, quietly.', 'Lost, are ye. Try followin someone. That is my whole method.'],
    win: ["Out. I'll be stealin that route.", 'Escaped. Copied it down. Thanks.', 'Ye got out. Good. Now I know the way too.'],
    fast: ['Faster than me. Ach. I will claim I let ye.', 'Under my time. Must be my route ye used.', 'Quick. Suspiciously quick. Did ye copy someone?'],
    locked: ["That one's locked. Mine first.", 'Not yet. Finish robbin me before ye rob them.', 'Closed. This maze is open. Get on with it.'],
    next: ['Go on. The next one is harder. I copied it myself.', 'Off ye go. Take the route with ye, I did.'],
  },
  'oogh-iv': {
    greet: ['Zug maze. Zug make with stick. Big stick.', 'You in Zug maze now. Zug not know way out either.', 'Welcome. Walls hard. Zug test.'],
    start: ['You move. Good. Zug watch.', 'Go go go. Zug cheer.', 'Moving. Zug proud already.'],
    hint: ['Hint? Zug give hint. Zug point. There.', 'Red line. Zug like red. Red is fire color.', 'Zug help. Zug not tell anybody.'],
    solve: ['Zug show whole way. Zug smart today.', 'Zug solve. You watch. No prize.', 'There. All the way. Zug tired now.'],
    slow: ['Still inside? Zug wait. Zug good at wait.', 'Long time. Zug go find snack. Zug back.', 'You lost? Zug lost too. Zug not say.'],
    win: ['Out! You out! Zug clap!', 'You find exit. Zug never find exit. Zug happy for you.', 'Escape! Zug yell it. ESCAPE!'],
    fast: ['Faster than Zug. Zug not fast. Still good.', 'Quick! Zug blink and you gone.', 'Under Zug time. Zug time was long. Still. Good.'],
    locked: ['No. That one shut. Zug maze first.', 'Locked. Zug not have key. Get out of Zug maze, then key.', 'Not yet. Zug first. Zug important.'],
    next: ['Go next. Next being less nice. Zug warn.', 'Bye. Zug wave. Zug keep waving.'],
  },
  'prearth': {
    greet: ['My maze. The rock lands in three minutes. Move.', 'Welcome to the floor. The exit is somewhere past the lava.', 'Sit? No. Run. Everything here runs.'],
    start: ['There we go. Keep the beat.', 'Moving. Faster. The sky is not waiting.', 'First step. Good. Do a thousand more.'],
    hint: ['A hint. The sky gives hints too. They are loud.', 'Half the route. The rest is a dance.', 'Fine. Red line. Follow it like a tail.'],
    solve: ['I will run you out. It does not count. Nothing counts when the sky falls.', 'Solved. By me. No trophy.', 'There. The whole way. Fast, like everything here.'],
    slow: ['Still inside. The rock is closer than you are to the exit.', 'Forty-five seconds. That is half a song on Prearth.', 'Lost. Fine. Dance while you are lost.'],
    win: ['Out! Before the rock. Barely.', 'Escaped. The sky noticed. It is still coming.', 'You made it out. Loud. The way we like it.'],
    fast: ['Faster than me, and I have claws. Respect.', 'Under my time. The rock is impressed.', 'Quick. Good. The sky rewards quick.'],
    locked: ['Not yet. Out of my maze first.', 'That one is shut. The rock will open it later.', 'Locked. Finish here. Then there.'],
    next: ['Go. The next one is colder. Keep the beat anyway.', 'Off you go. Tell them Prearth sends its rock.'],
  },
  'that-other-planet': {
    greet: ['Unit 7 maze. Entry is free. Exit is billable.', 'Welcome. The optimal path is known. It is available for a fee.', 'Proceed. Every wall you touch is logged.'],
    start: ['Movement detected. Timer started. Billing started.', 'First step logged. Suboptimal, but logged.', 'Proceeding. Please keep to the corridors.'],
    hint: ['A hint. The fee is noted on your invoice.', 'Half the route, provided. Consulting rate applies.', 'Hint delivered. Efficiency, purchased.'],
    solve: ['Full solution delivered. This does not count as your completion. It counts as my fee.', 'Solved by Unit 7. Credit: Unit 7.', 'The optimal route. Observe. Pay later.'],
    slow: ['Forty-five seconds. Your rate per second is unchanged.', 'Still inside. The invoice grows with you.', 'Inefficient. Noted. Billed.'],
    win: ['Exit confirmed. Your total is on the back.', 'Complete. Time logged. Invoice issued.', 'Out. Acceptable. Payment terms apply.'],
    fast: ['Faster than Unit 7. Recalculating my own rate.', 'Under my time. Anomaly logged. Discount: none.', 'Efficient. I respect it. I bill it.'],
    locked: ['That maze is not yet available. Complete this one first.', 'Locked. Sequential access only.', 'Not open. This one is. Proceed.'],
    next: ['Proceed to the next maze. Rates increase.', 'Go. The next consultant is less reasonable.'],
  },
  'figuria': {
    greet: ['My maze. Snap-fit walls. Most of them hold.', 'Welcome. The exit is the one piece that fits.', 'Come in. Mind the loose parts.'],
    start: ['Moving. Good articulation.', 'First step. Joints working.', 'There you go. Snap, snap.'],
    hint: ['A hint. Half the build, shown.', 'Fine. The red line. Like the instructions, but honest.', 'Hint. I would have dug through the pile for that.'],
    solve: ['I will walk you out. Does not count. A kit built by someone else is not yours.', 'Solved. By me. Put it on the shelf.', 'There. Every piece in place. Watch.'],
    slow: ['Still inside. Missing a part, I think. Keep looking.', 'Forty-five seconds. The pile is deep.', 'Lost. Happens. Something is always missing.'],
    win: ['Out. Clean build.', 'Escaped. Every piece fit.', 'You found the way. Snap. Complete.'],
    fast: ['Faster than me. I was looking for my arm.', 'Under my time. Good hinge on you.', 'Quick. That fit first try.'],
    locked: ['Not yet. Finish this build first.', 'That one is still in the box.', 'Locked. One kit at a time.'],
    next: ['Go on. The next one has more parts.', 'Off you go. Take a spare, you will need it.'],
  },
  'dens-crevice': {
    greet: ['My cave. My maze. The gold is at the end. You will not get it.', 'Enter. The walls are warm for a reason.', 'A visitor. The maze is long. The fire is longer.'],
    start: ['Moving. Brave. Briefly.', 'First step into the cave. Many have taken it. Few mention the second.', 'There. Begin. I am watching from above.'],
    hint: ['A hint. The dragon gives nothing free. This is nearly nothing.', 'Half the route. Burned into the floor.', 'Fine. The red line. The fire drew it.'],
    solve: ['I will show you out. It does not count. Dragons do not share wins.', 'Solved. By me. Applause is customary.', 'There. The whole way. Magnificent, is it not.'],
    slow: ['Still inside. The cave keeps what the cave likes.', 'Forty-five seconds. Warmer yet?', 'Lost in my cave. Many are. Comfortable, eventually.'],
    win: ['Out. The gold stays. Fine. Go.', 'Escaped the cave. The fire remembers your name.', 'You got out. Hm. The hoard is unmoved. I am, a little.'],
    fast: ['Faster than a dragon. In my own cave. Tell no one.', 'Under my time. Impossible. And yet.', 'Quick. The fire did not even catch up.'],
    locked: ['Not yet. Out of my cave first.', 'That one is sealed. This one is open. Burn through this one.', 'Locked. The gold says so.'],
    next: ['Go. The next cave is colder and the host is softer.', 'Off you go. Leave the gold where you found it.'],
  },
  'heliumdrum': {
    greet: ['My maze. Soft walls, I promise. Mostly.', 'Welcome. Please do not bump anything. Including me.', 'Hi. The exit is somewhere gentle.'],
    start: ['Moving. Gently, please.', 'First step. Okay. Okay. Good.', 'There you go. Float, if you can.'],
    hint: ['A hint. Softly. Half the way.', 'Fine. The red line. It looks sharp but it is not.', 'Hint. Please do not tell the corners.'],
    solve: ['I will float you out. It does not count. I would feel bad counting it.', 'Solved. By me. Quietly.', 'There. The whole way. No sharp turns. Well, some.'],
    slow: ['Still inside. That is all right. Drifting counts.', 'Forty-five seconds. Breathe. Not too much.', 'Lost. Gently lost. Keep going.'],
    win: ['Out! Oh. Nobody pop anything.', 'Escaped. Softly. Lovely.', 'You floated out. I am so relieved.'],
    fast: ['Faster than me. I drift, you know.', 'Under my time. Oh. Oh, well done.', 'Quick. Like a breeze. A careful breeze.'],
    locked: ['Not yet. Finish mine first. Gently.', 'That one is closed. This one is soft. Stay.', 'Locked. Sorry. Sorry. Keep going here.'],
    next: ['Go on. The next one has edges. Be careful.', 'Off you float. Mind the needles.'],
  },
  'washy-washy-ii': {
    greet: ['My maze. Back-room rules. Find the door.', 'Welcome. The way out is locked from inside. Find the key.', 'Sit down. No. Stand up. Run.'],
    start: ['Moving. Chin down.', 'First step. The Wall is watching.', 'There you go. Keep your guard up.'],
    hint: ['A hint. The Wall remembers who asked.', 'Half the route. The other half costs you.', 'Fine. The red line. Do not get used to help.'],
    solve: ['I will walk you out. Does not count. The Wall knows.', 'Solved. By me. Your name goes nowhere.', 'There. The whole way. Street rules: watch and learn.'],
    slow: ['Still inside. The back room is comfy, is it.', 'Forty-five seconds. The Wall is warming up a spot.', 'Lost. Happens to the tough ones too.'],
    win: ['Out. Clean. The Wall spells your name right.', 'Escaped. Ledgered.', 'You found the door. Respect.'],
    fast: ['Faster than me. I know the back room and you beat me. Hm.', 'Under my time. The Wall is impressed. Rare.', 'Quick. Clean. Ledgered twice.'],
    locked: ['Not yet. Out of my room first.', 'That one is locked. This one is open. Door is that way. Somewhere.', 'Locked. One room at a time.'],
    next: ['Go on. The next room is meaner.', 'Off you go. The Wall has room for more.'],
  },
  'yarnia': {
    greet: ['My maze, dear. I knitted it. Mind the loose ends.', 'Come in, love. The exit is where the pattern says. I will not tell you.', 'Welcome. Everything in here is wool. Everything.'],
    start: ['Moving, dear. Good. Even steps.', 'First row. Lovely.', 'There you go, love. Follow the thread.'],
    hint: ['A hint, dear. I will remember you asked.', 'Half the pattern, shown. The rest you knit yourself.', 'Fine, love. The red thread. Mind it does not tangle.'],
    solve: ['I will walk you out, dear. It does not count. Finished by me is not finished by you.', 'Solved, love. By me. I keep the pattern.', 'There. The whole thing. Tidy, is it not.'],
    slow: ['Still inside, dear. The wool is warm at least.', 'Forty-five seconds, love. Patience. I have plenty.', 'Lost in the yarn. It happens. Keep pulling.'],
    win: ['Out, dear. Cast off. Lovely.', 'Escaped, love. I shall remember how.', 'You found the end of the thread. Well done, dear.'],
    fast: ['Faster than me, dear. I was counting stitches. Hm.', 'Under my time, love. I will remember that too.', 'Quick. Very neat. Suspicious, but neat.'],
    locked: ['Not yet, dear. Finish mine first.', 'That one is tied off. This one is open.', 'Locked, love. Patience. I have plenty.'],
    next: ['Go on, dear. The next one is knitted tighter.', 'Off you go, love. I have your measurements.'],
  },
  'hungary': {
    greet: ['My maze. Fresh today. Move before it goes stale.', 'Welcome. The exit is where dessert is.', 'Come in. The walls are crusty. On purpose.'],
    start: ['Moving. Good. Before it cools.', 'First bite. Keep going.', 'There you go. Crisp.'],
    hint: ['A hint. Half the recipe.', 'Fine. The red line. Follow the crumbs.', 'Hint delivered. Warm.'],
    solve: ['I will walk you out. It does not count. A meal somebody else ate is not yours.', 'Solved. By me. Plate cleared.', 'There. The whole route. Served.'],
    slow: ['Still inside. Getting stale yet?', 'Forty-five seconds. The oven is off. Hurry.', 'Lost. Fine. Everything spoils. Finish anyway.'],
    win: ['Out. Fresh to the end.', 'Escaped. Dessert is yours.', 'You made it out before it spoiled. Good value.'],
    fast: ['Faster than me. I am a snack and you beat me. Hm.', 'Under my time. Still crisp.', 'Quick. Nice bite.'],
    locked: ['Not yet. Clear this plate first.', 'That one is in the oven. This one is served.', 'Locked. One course at a time.'],
    next: ['Go on. The next one is spicier.', 'Off you go. Take a crumb for the road.'],
  },
  'guffaw-7': {
    greet: ['My maze. Tough room. No exits marked. That is the bit.', 'Welcome. Find the door. Do not laugh on the way, the walls hate it.', 'Sit down. No. Walk. The act is you walking.'],
    start: ['Moving. The warm-up. Nobody claps for the warm-up.', 'First step. Hold for laughter. Nothing. Keep going.', 'There you go. Timing.'],
    hint: ['A hint. The heckler in the booth helps you. Tough room.', 'Half the route. The punchline is still yours to find.', 'Fine. The red line. That is the callback.'],
    solve: ['I will walk you out. Does not count. Somebody else did the bit.', 'Solved. By me. Tip your knights.', 'There. The whole route. Big finish. Nobody laughed.'],
    slow: ['Still inside. Bombing. Beautifully.', 'Forty-five seconds. That is a long pause even for me.', 'Lost. Crowd work time. Hi. Keep walking.'],
    win: ['Out. Thank you, you have been wonderful. Drive safe.', 'Escaped. The room went quiet, in a good way.', 'You found the exit. That is the show.'],
    fast: ['Faster than me. I was doing crowd work.', 'Under my time. Somebody finally laughed. It was me.', 'Quick. Tight set.'],
    locked: ['Not yet. Finish my set first.', 'That one is dark tonight. This one is open mic.', 'Locked. One act at a time.'],
    next: ['Go on. The next room is tougher. They all are.', 'Off you go. Tell them Guffaw-7 sent you. They will not laugh.'],
  },
  'spee-ider-grove': {
    greet: ['My maze. Everything in it is connected. To me.', 'Welcome. Mind the threads. They are the walls.', 'Come in, come in. The exit moves. Plot twist.'],
    start: ['Moving. Fast. Good.', 'First step. The web felt it.', 'There you go. Do not look at the corners.'],
    hint: ['A hint. Half the web, shown.', 'Fine. The red thread. I spun it.', 'Hint. Fast. Like everything here.'],
    solve: ['I will walk you out. Does not count. The web knows who moved.', 'Solved. By me. Wrapped and tidy.', 'There. The whole route. Spun in three minutes.'],
    slow: ['Still inside. The web tightens, you know.', 'Forty-five seconds. The web is humming.', 'Lost in the threads. Do not struggle. Or do.'],
    win: ['Out. You cut the right thread.', 'Escaped. The web shivered.', 'You found the way. Plot twist: I let you. No I did not.'],
    fast: ['Faster than me. In my own web. Hm.', 'Under my time. The threads are impressed.', 'Quick. Faster than eight legs.'],
    locked: ['Not yet. Out of my web first.', 'That one is wrapped. This one is open.', 'Locked. One web at a time.'],
    next: ['Go on. There is no next. You are at the end of the route.', 'That was the last one. The whole route, walked. Now sit down and play me at chess.'],
  },
};
