/* OVER THE BOARD: what the thirteen beings say. Written for each being, never generated.
   {piece} is the piece that was taken. A line is never said twice in one game while an unsaid one is left in its pool.

   When each kind fires (game.js):
     greet     a new game                      think    an ordinary move, mid-game
     open      its first few moves             late     the endgame (few pieces left, or past move 28)
     ahead     it is clearly winning           behind   it is clearly losing
     capture   it takes a piece                lose     you take one of its pieces
     check     it gives check                  checked  you give check
     castled   it castles                      ucastle  you castle
     promo     it promotes a pawn              upromo   you promote a pawn
     blunder   you hang material               good     you find a strong move
     win / lost / resign / taken / draw        event    its own moment (see beings.js) */

export const LINES = {
  'planet-zee': {
    greet: ["Sit. There's time. There has always been time. It's most of what I have.", 'White is yours. Move when you like. I will still be here.', 'Take a number. Oh, you have one. Then we begin.', 'Welcome to the queue. The board is the queue. Everything is.', 'I processed the last player in 1987. Please do not feel rushed.'],
    open: ['An opening. They all look the same from the back of the line.', 'Form a line. Your pawns already have.', 'Early days. Nothing on Planet Zee has ever been early.', 'Noted: you moved first. It is on the record now.'],
    think: ['Hm. This is a long line. I am taking a number.', 'No rush. Nothing on this planet has ever been rushed.', 'Considering. Please do not wait up.', 'One moment. The moment may be long.', 'I am filing this position. Under pending.', 'Let me look at that the way I look at everything. Slowly, twice.', 'Your move has been received. A response will follow in due course.', 'Patience is the native language here. I am fluent.', 'I have outwaited empires. I can outwait a knight.'],
    late: ['Fewer pieces. Shorter line. Still a line.', 'The end approaches. It always does. It is the one appointment everyone keeps.', 'This is the part where most people get tired. I do not get tired.', 'Nearly done. Nearly is a place I live.'],
    ahead: ['I appear to be winning. I will believe it when the paperwork clears.', 'Ahead. It happens, roughly once a century.', 'The line is moving in my favor. Do not get up.', 'Comfortable. The dead are always comfortable.'],
    behind: ['Behind. I have been behind since before you were born. It suits me.', 'You are ahead. Enjoy it while the ink is wet.', 'A setback. I will file an appeal, around the next century.', 'Losing, slowly. My favorite speed.'],
    capture: ['Your {piece}, processed. Next in line.', 'Taken. Slowly, which is how I take everything.', 'That {piece} had been waiting a while. Now it is done waiting.', 'One {piece}, received. Stamped. Shelved.', 'The {piece} has been reassigned. To me.', 'Your {piece} is now a former {piece}. I keep the records.', 'Collected. The {piece} did not complain. They never do.'],
    lose: ["Ah. You took my {piece}. I'll file that under later.", 'A {piece} gone. It was already decaying, if that helps.', "Noted. I've lost bigger things to longer queues.", 'My {piece}. Well. It had a good run, as runs go here.', 'That {piece} will be missed, by nobody, for a long time.', 'Logged. One {piece}, departed. Cause: you.', 'Fine. The {piece} can wait in the other line now.'],
    check: ['Check. Do sit down. This will be a while.', 'Your king is in check. Take your time. I will.', 'Check. The king has been asked to step forward.', 'Check. Please have your documents ready.', 'Check. No, there is no rush. There is also no exit.'],
    checked: ['Check. Brisk of you. Almost rude.', 'Check. My king has been summoned. He hates that.', 'Check. I shall move him, eventually.', 'Check, you say. I heard you the first time. Centuries ago.'],
    castled: ['Castled. The king is now at the back of the line, where it is safest.', 'My king has taken a seat. He will not be called for some time.', 'Castled. Filed under: not today.'],
    ucastle: ['Castled. Smart. Hide the king. They always find him eventually.', 'Your king retires behind the desk. I know that desk.', 'A castle. Very cozy. Very temporary.'],
    promo: ['A new queen. Promoted from pawn, after a very long wait.', 'Promotion. In this office, that takes eight squares and a lifetime.'],
    upromo: ['A new queen for you. Congratulations. The paperwork is enormous.', 'Promoted. Somebody finally got to the front of the line.'],
    blunder: ['Oh. You left that there. I will take it, when I get around to it.', 'That was a mistake. Do not worry. It will be in the file forever.', 'A free {piece}? I do not usually get gifts.', 'You hung it. I have all day to pick it up.'],
    good: ['Hm. That was good. I will note it under rare.', 'A real move. From the living. Interesting.', 'Sharp. I did not expect that from this side of the desk.', 'Well found. Most people never find anything here.'],
    win: ['Checkmate. Thank you. Please take a ticket for the next one.', 'Mate. The line has closed. It will reopen when you are ready to lose again.', 'Checkmate. Stamped, dated, filed. Next.'],
    lost: ["Mate. Someone finally did it. I've been waiting a long time for that.", 'Mate. You got to the front of the line. Nobody ever does.', 'Checkmate. I am, for once, surprised. Mark the date.'],
    resign: ['I resign. Everything ends. I just hoped to watch it take longer.', 'I resign. Put it in the file. The file is very large.'],
    draw: ['A draw. Nobody moved in the end. My favorite kind of game.', 'A draw. We can wait together. I am good at that.'],
    taken: ['You resigned. Most people wait longer. I admire the efficiency.', 'Resigned. Noted. The line moves on without you.'],
  },

  'yaaarghs-revenge': {
    greet: ["Sit, and mind the fine print. There isn't any. That's the trick.", 'Yaaargh. Go on and move. I will be copying your homework.', "Welcome aboard. Everything on this ship was somebody else's first.", 'Make a move. A good one, mind. I plan on using it.', "Ye brought a plan? Lovely. Soon it'll be mine."],
    open: ['An opening. Yours, for now.', "Interesting start. I've seen it before. I'll see it again, from my side.", "Ye play that? Funny. So do I, as of now.", 'First moves. The ones ye borrowed, I mean.'],
    think: ['Hold on. Lemme see what ye just did there.', 'Studying your last move. Real close. Like it was mine.', 'Thinkin. Mostly about whose idea this was. Yours.', 'Lemme copy that down. Slower. Neater.', 'A moment. Me notes on ye are long.', "Hm. If I were you, and I nearly am, what would I do.", 'Thinkin like ye, but with better hair.', "Give us a second. Imitation takes care.", 'Checking the manifest. Everything good on this board came from somewhere.'],
    late: ['Few pieces left. Fewer ideas to steal. Pity.', "The end. I'll be takin the credit for however it goes.", "Endgame. I've copied this one from a book I didn't pay for.", 'Nearly over. Mind, I said that about the last ship too.'],
    ahead: ["Ahead. Funny how that happens when I use your moves.", "Winnin. With a borrowed plan. The best kind.", 'Ye should see yer face. I am, in a way.', "I'm up. Thank ye for the ideas."],
    behind: ['Behind. Must be the one move I did not copy.', "Losin, am I. Give us a minute to steal a better plan.", "Ye're ahead. Keep it up. I'm watchin how.", 'Down a bit. Nothing a little salvage cannot fix.'],
    capture: ['That {piece} is mine now. Finders keepers, and I found it.', 'Salvage rights. Thank ye for the {piece}.', 'Fine {piece}. Better looking on my side.', 'A {piece}, liberated. That is the word we use.', 'Yoink. One {piece}. Receipt not included.', "The {piece} came quietly. They usually do.", 'Mine. The {piece}, I mean. And the idea.'],
    lose: ["Ye took me {piece}. I'll take yer next idea. Fair's fair.", "A {piece}? I'll be wantin that back, with interest.", 'Ach. Every cut costs a cut. Noted.', "Me {piece}. Well. It was stolen anyway.", "Took me {piece}, did ye. I've a list. Ye're on it twice now.", 'Fine. The {piece} was a copy. The original is safe.', 'That stung. Mostly me pride, which I also stole.'],
    check: ['Check, and I copied it from you. You are welcome.', "Yer king's in a spot. Mine was in it first.", 'Check. Saw it in a book. Did not read the book.', "Check. Ye taught me that one. Thanks.", 'Check. Where did I get that? Somewhere good.'],
    checked: ['Check? That is what I was about to do. Rude.', "Check. I'll be borrowing that.", 'Check. Ach. Mine own trick, turned on me.', "Check. Lovely. Mind if I take notes?"],
    castled: ['Castled. Like ye did. Or were about to.', "Me king's behind the rook now. Learned that from a man I robbed.", 'Castled. The move is safe. The idea is stolen.'],
    ucastle: ["Castled. Nice. Watch me do the same, only cheaper.", "Ye tucked the king away. I'll find the key.", 'A castle. Good. I like a thing with a lock to pick.'],
    promo: ['A new queen. Took her from a pawn that took her from you.', 'Promoted. The crown fits. It fit the last owner too.'],
    upromo: ['A queen for you. Hold onto her. I mean that literally.', "Promoted. Very grand. I'll be wanting one."],
    blunder: ["Ye left that hangin? Don't mind if I do.", 'A free {piece}. Even I would not have the nerve to call that mine.', 'Oh ye dropped something. Finders keepers.', "That was careless. I've copied the careless too."],
    good: ["Ooh. That's good. That's mine now.", 'A fine move. Say it again slower so I can write it down.', "Now that I did not see. Which means ye did. Which means I will.", 'Sharp. I am stealin that, with yer permission. Or without.'],
    win: ['Mate. I barely had to think. Ye did the hard part.', "Mate. Yer own plan, flipped. Honest work, nearly.", 'Checkmate. Thank ye for the moves. All of them.'],
    lost: ["Mate, clean. I'll be stealin that move for the next one.", 'Mate. Ye kept one idea I could not copy. Well played.', "Checkmate. Ach. Somebody finally read the fine print."],
    resign: ["I'm out. Keep the board. I'll keep the pieces.", 'I resign. No plan left to borrow.'],
    draw: ['A draw. Honest work, for once. Felt strange.', "A draw. We copied each other into a corner."],
    taken: ["Ye fold. Fine. I'll keep the board and the credit.", 'Resigned. Then the win is mine. By default, which counts.'],
  },

  'oogh-iv': {
    greet: ['Zug play. Zug like shiny horse.', 'You sit. Zug push wood. Wood is chess.', 'Zug here. Zug ready. Zug not sure for what.', 'Board flat. Good. Zug like flat.', 'Zug see pieces. Zug want pieces. Game start.'],
    open: ['Zug move pawn. Pawn small. Zug start small.', 'First moves. Zug remember these. Mostly.', 'Zug push wood forward. Forward is good.', 'Zug see your move. Zug do move too.'],
    think: ['Zug think. Head hurt a little.', 'Hmm. Zug look at piece. Piece look back.', 'Wait. Zug find move. Move hiding.', 'Zug think hard. Smoke come out ears. Normal.', 'Zug count pieces. Zug lose count. Zug count again.', 'Quiet. Zug thinking. Zug thinking is loud inside.', 'Which one shiny. Zug want shiny one.', 'Zug has idea. Idea gone. Zug has other idea.', 'Hmm. Hmm hmm. Zug almost there.'],
    late: ['Not many pieces. Zug can count now. Good.', 'Board empty. Zug see everything. Zug still confused.', 'End close. Zug feel it. Also hungry.', 'Few pieces left. Zug protect them like fire.'],
    ahead: ['Zug winning? Zug winning! Nobody tell Zug how.', 'Zug has more. More is good. Zug keep more.', 'Zug ahead. Zug not know why. Zug not ask.', 'Good for Zug. Bad for you. Zug sorry. Little.'],
    behind: ['Zug losing. Zug not like. Zug push harder.', 'You have more. Zug count twice. Still more.', 'Bad for Zug. Zug keep going. Zug stubborn.', 'Zug behind. Zug want fire. No fire. Zug play.'],
    capture: ['Zug take {piece}! Zug take! Good!', 'Smash. Zug keep it.', 'Ooh. Shiny. Mine now.', 'Zug grab {piece}. Zug happy.', 'One {piece} for Zug. Zug put in pocket. Zug has no pocket.', 'Got it. The {piece}. Zug hold tight.', 'Yoink. {piece} come live with Zug now.'],
    lose: ['Zug {piece} gone. Zug sad. Little.', 'You take Zug {piece}? Rude. Zug do it back.', "Ow. Whose idea that? Zug's idea. Ow.", 'Zug lose {piece}. Zug blink. Still gone.', 'Hey. Zug liked that {piece}. Not fair.', 'Zug {piece} go away. Zug wave bye.', 'No. Zug {piece}. Zug pout. Zug play anyway.'],
    check: ['Zug poke your king. Poke poke.', 'Bonk. King in trouble. Zug proud.', 'Zug say check. Zug learn word today.', 'Your king scared. Zug did that.', 'Check! Zug yell it. Feel good.'],
    checked: ['Your king hit Zug king. Why?', 'Zug king in trouble. Zug king run.', 'Check on Zug. Zug not like. Zug move king somewhere.', 'Ow. Zug king. Leave Zug king alone.'],
    castled: ['Zug hide king behind rock. Rook. Rook is rock.', 'Zug do the hop move. King safe. Zug clever.', 'Castle. Zug not know what castle is. Zug did it anyway.'],
    ucastle: ['You hide king. Zug find king later.', 'King go hide. Zug see where.', 'Hop move. Zug want hop move too.'],
    promo: ['Pawn become queen! Zug make queen! Zug magic.', 'Small piece go big. Zug proud of small piece.'],
    upromo: ['You make queen. Zug want one. Zug jealous.', 'Pawn grow up. Zug wipe tear.'],
    blunder: ['You leave {piece}. Zug take. Easy.', 'Free thing? Zug like free thing.', 'You forget piece. Zug not forget. Zug remember shiny.', 'Oops for you. Yay for Zug.'],
    good: ['Oh. That good move. Zug not see that.', 'You smart. Zug think hard now.', 'Hmm. That hurt Zug brain. Good move.', 'Zug clap. Zug not know why. Good move.'],
    win: ['Zug win! Zug win! Zug tell everybody. Zug has no everybody. Zug tell you.', 'King stuck. Zug did it. Zug dance.', 'Zug win. Zug not sure how. Zug take it.'],
    lost: ['King stuck. Zug lose. Fire now? No? Okay.', 'Zug lose. You good. Zug eat now.', 'Zug king trapped. Zug sad. Zug play again later.'],
    resign: ['Zug done. Too many pieces. Zug go eat.', 'Zug give up. Zug tired. Zug nap.'],
    draw: ['Nobody win? Zug fine with it. Zug still eat.', 'Draw. Zug not know draw. Zug like it.'],
    taken: ['You stop? Zug win? Zug take it. Zug win.', 'You quit. Zug confused. Zug happy.'],
  },

  'prearth': {
    greet: ['Welcome to the dance floor. The floor has a deadline.', "Asteroid's coming. Pick a side and make it count.", "Sit down. Or dance. Either way the rock lands at the same time.", 'Last night on Prearth. Every night is. Move.', 'The sky is loud tonight. Play louder.'],
    open: ['Opening moves. The band is warming up.', 'Early. The sky is still mostly sky.', 'First steps. Keep the beat.', "Here we go. The rock won't wait and neither do I."],
    think: ["Hold the beat. I'm hunting the next move.", "Tail's swinging. That means I'm thinking.", 'Mm. Smells like an opening.', 'Thinking fast. Everything here is fast.', 'One second. The drop is coming.', 'Finding the move. It is somewhere in the noise.', 'Claws tapping. Patience is not a Prearth thing.', 'Give me a beat. One beat. There.', "I'm circling. Dinosaurs circle. It is in the manual."],
    late: ['Few pieces left. Fewer than the minutes.', 'Endgame. The sky is orange now. Hurry.', 'Nearly done. So is everything else here.', 'Last dance. Make it a good one.'],
    ahead: ['Ahead. The rock will not care, but I do.', 'Winning. Loud. The way we do.', "I'm up. Dance while you can.", 'This is going my way. Enjoy the view, it is on fire.'],
    behind: ['Behind. Fine. We go extinct fighting.', 'You are ahead. The asteroid is ahead of both of us.', 'Losing, am I. Turn the music up.', 'Down. Not out. Never out, until the sky says so.'],
    capture: ['Chomp. Your {piece} never saw me.', 'Clean bite. That {piece} was a good meal.', 'Snap. Next.', 'The {piece}? Eaten. Thank you.', 'One {piece}, gone with a crunch.', 'Caught your {piece} mid-step. Good dancer. Bad luck.', 'Teeth. {piece}. Done.'],
    lose: ["Take it. I've got plenty more where that came from.", 'A {piece}? Costs nothing when the sky is on fire.', 'You bite hard. I like that in a party guest.', 'My {piece}. Gone. So is the dinosaur that cared.', 'Fine. The {piece} was slowing the dance.', 'Lost a {piece}. The rock will take the rest anyway.', 'Ouch. Good. Keep the pressure up.'],
    check: ["Check. Run, king. The beat's fast.", 'Claws out. Check.', 'Check. Feel the sky coming down.', 'Check. Your king is the only thing moving slower than me.', 'Check! Roar included.'],
    checked: ['Ooh, teeth. Check noted.', 'Check. My king is dancing. Badly.', 'Check. Good. A chase.', 'Check on me. Cute. The sky is scarier.'],
    castled: ['Castled. Even a dinosaur knows where the bunker is.', 'King behind the rook. Rock behind the sky. Everybody hides.', 'Castled. Now the real stomping starts.'],
    ucastle: ['Castled. Hiding from me, or the asteroid?', 'King in the bunker. The bunker will not hold.', 'A castle. Nice. I eat castles.'],
    promo: ['A new queen. Hatched from a pawn. Prearth works fast.', 'Promoted. Evolution in eight squares.'],
    upromo: ['A queen for you. Impressive. Still extinct by midnight.', 'Promoted. Nice. The sky noticed.'],
    blunder: ['You left that out. The sky is falling and so is your {piece}.', 'A free {piece}. Chomp.', 'Careless. On Prearth, careless gets eaten.', 'You dropped it. I picked it up with my teeth.'],
    good: ['Oh. That was sharp. Sharper than me, and I am all teeth.', 'Good move. The band stopped to look.', 'That one stung. Nice.', 'You can dance. Noted.'],
    win: ["Mate. That's the drop. Hear it?", 'Checkmate. The rock can come now. I am done.', 'Mate. Roar. Then the sky.'],
    lost: ["Well bitten. Mate. Next song's on me.", 'Mate. You out-danced a dinosaur. Rare.', 'Checkmate. I went down swinging my tail. As planned.'],
    resign: ['I am done. Nothing left to throw at you. Respect.', 'I resign. The sky can finish it.'],
    draw: ['A draw. The asteroid called. It is rescheduling.', 'A draw. Nobody wins on Prearth. Everybody dances.'],
    taken: ['Tapping out. Smart. The sky was falling on your side.', 'You resign. Fine. More floor for me.'],
  },

  'that-other-planet': {
    greet: ['Unit 7 is ready. Consultation time is billable from the first move.', 'Greetings. If this ends in under forty moves, the invoice is reduced.', 'Session open. Rate card available on request. Request is also billable.', 'Welcome. Please note that silence is charged at the standard rate.', 'Unit 7, online. Your account has been created. It is already overdue.'],
    open: ['Opening phase. Standard fees apply.', 'An opening. Catalogued. Seventeen known continuations. All itemized.', 'Early position. Consulting the shelf. The shelf charges by the minute.', 'Your first move has been logged. So has the cost of logging it.'],
    think: ['Analysis in progress. I will explain it afterward. At length.', 'Computing. Each second of this is itemized.', 'Seventeen candidate moves. Sixteen are inferior. Please hold.', 'Processing. The meter is running.', 'Evaluating. Your patience will appear as a line item.', 'One moment. Precision costs extra, and I only do precision.', 'Running the numbers. The numbers are also running.', 'Computing optimal response. Suboptimal responses are cheaper. You did not choose cheaper.', 'Analysis at 60 percent. Billing at 100.'],
    late: ['Endgame. Reduced material. Rates unchanged.', 'Fewer pieces. Fewer variables. Same fee.', 'Final phase. The invoice is being drafted.', 'Approaching conclusion. Please have payment ready.'],
    ahead: ['Advantage: Unit 7. Expected. Documented.', 'I am ahead. This was in the projection.', 'Winning position. The surcharge for winning is modest.', 'Ahead by a margin I could explain. For a fee.'],
    behind: ['Deviation detected. I am behind. This was not projected.', 'Losing. Recalculating. Recalculation is billable.', 'You are ahead. The invoice remains unchanged.', 'Behind. Adjusting parameters. Adjusting fees.'],
    capture: ['Your {piece} has been removed. Replacement cost is not my concern.', 'Capture executed. Net gain recorded.', 'Efficient. Your {piece} was an input I no longer require.', 'One {piece}, decommissioned.', 'The {piece} has been written off. Yours, not mine.', 'Acquisition complete. One {piece}. No warranty.', 'Your {piece} is now a line on my ledger.'],
    lose: ['Loss of {piece} logged. Deviation from expected parameters: yours.', 'Unexpected. Adjusting. This will appear on your invoice.', 'Acceptable. That {piece} had a poor return.', 'A {piece}, lost. Depreciated anyway.', 'Noted. One {piece}. Insurance will cover it. You are the insurance.', 'Asset removed. Reallocating.', 'That {piece} was underperforming. Thank you for the write-off.'],
    check: ['Check. Your king is outside acceptable limits.', 'Check. I would explain the reason, but that is a separate fee.', 'Check. Compliance is now mandatory.', 'Check. Your king has been flagged for review.', 'Check. Please respond within one move.'],
    checked: ['Check detected. Responding within tolerance.', 'Check. Minor. Logged.', 'Check. My king will relocate. Relocation is billable to you.', 'Check. A notification, not a problem.'],
    castled: ['Castled. The king is now in a secure facility.', 'Castling complete. Access restricted.', 'King relocated. Rook reassigned. Efficient.'],
    ucastle: ['Castled. A reasonable allocation of resources.', 'Your king is in storage. Storage fees apply.', 'Castled. Standard procedure. I approve, for a fee.'],
    promo: ['Promotion. A pawn has been upgraded to queen. The upgrade was not free.', 'New queen. Capital expenditure, recouped shortly.'],
    upromo: ['Promotion noted. Congratulations. The tax is substantial.', 'A new queen on your side. Reassessing. Rebilling.'],
    blunder: ['Error on your side. Logged. Exploited.', 'You left a {piece} unprotected. I do not leave things unprotected. Or unbilled.', 'A free {piece}. There is no such thing. You will be charged for the lesson.', 'Suboptimal. Significantly. Thank you.'],
    good: ['A strong move. Unexpected. Recalculating.', 'Correct. That was the best available. I would have charged for that.', 'Efficient. I respect efficiency. I bill it too.', 'Noted. A good move. It will not change the invoice.'],
    win: ['Checkmate. Your total is 90,000 Wishbones. Payment terms are on the back.', 'Checkmate. Session closed. The invoice is not.', 'Mate. Outcome as projected. Please pay at the desk.'],
    lost: ['Checkmate. Result recorded in your favor. Please disregard the invoice.', 'Mate. An anomaly. The refund will take six to eight centuries.', 'Checkmate. Loss logged. Fees waived. This is unprecedented.'],
    resign: ['I resign. The cost of continuing exceeds the expected return.', 'Resignation filed. Cheaper than losing slowly.'],
    draw: ['A draw. No party owes. I find this statistically irritating.', 'A draw. Balanced books. Unsatisfying.'],
    taken: ['Resignation noted. The invoice stands.', 'You resign. Efficient. The fee is unchanged.'],
  },

  'figuria': {
    greet: ['Nice board. Great articulation on those knights. Let us play.', "I'm missing a left arm somewhere in here. Ignore that.", 'Sit. Mind the small parts. Everything here is small parts.', 'Fresh out of the box. Let us see how long that lasts.', 'Good joints on you. Let us play.'],
    open: ['Opening. Pieces still in the package.', 'First moves. Everything snaps together, at the start.', 'Early. All my limbs are where I left them. For now.', 'An opening. Clean seams. Nice.'],
    think: ['Checking the joints on this position.', 'Snap fit. Snap fit. Not yet.', "Digging for the right piece. There's always one in there.", 'Thinking. One moment. My head is on a swivel, literally.', 'Testing the fit. Not that one. Not that one.', 'Looking through the pile for a move.', 'Hm. This needs the small screwdriver.', 'Articulating. That is what we call thinking.', 'Hold on. Something here is missing a peg.'],
    late: ['Few pieces left. Like the bottom of the bin.', 'Endgame. Missing parts everywhere. Mine and yours.', 'The pile is thin now. Every piece counts.', 'Nearly done. Nearly complete. Never complete.'],
    ahead: ['Ahead. All my parts are in. Most of yours are not.', 'Winning. Clean build.', 'This is coming together. Snap, snap.', "I'm up. Good hinge on this game."],
    behind: ['Behind. Missing parts. Still building.', 'You are ahead. Somewhere in the pile I have an answer.', 'Losing. Feels like a bad batch.', 'Down. Going back to the instructions.'],
    capture: ['Your {piece} came off clean. Good seam.', "Snap. That one's mine now.", 'Trade you. Wait, no. Just taking it.', 'One {piece}, popped off at the joint.', 'The {piece} goes in my bin now.', 'Detached. Your {piece}. Mine.', 'Got the {piece}. It fit perfectly, in my hand.'],
    lose: ['Took my {piece} off at the joint. Rude, but neat.', 'I needed that {piece}. It had the good hinge.', "Fine. Somewhere in the pile there's another one.", 'My {piece}. Gone. Add it to the missing-parts list.', 'A {piece}, lost. Builds have spares. Mine does not.', 'That {piece} was glued. Apparently not.', 'Hm. I liked that {piece}. Good paint.'],
    check: ['Check. Pieces fit.', "Your king's in the pose. Check.", 'Check. Snap.', 'Check. That one clicked in.', 'Check. Hold still, I am adjusting your king.'],
    checked: ["Check. Hope is a scam, but I'll keep digging.", 'Check. My king wobbles. Loose peg.', 'Check. Fine. Repositioning.', 'Check on me. Testing my joints, are you.'],
    castled: ['Castled. King and rook, snap-fit.', 'Two pieces, one click. Castled.', 'Castled. That is the kind of fit I like.'],
    ucastle: ['Castled. Clean assembly.', 'King and rook swapped. Nice articulation.', 'A castle. Solid. Solid things come apart too.'],
    promo: ['Promoted. A pawn with a new head. Queen head.', 'New queen. Swapped the part. Perfect fit.'],
    upromo: ['A new queen. Good upgrade. Great paint.', 'Promoted. You found the rare part.'],
    blunder: ['You left that loose. Loose parts fall off.', 'A free {piece}? Into the bin.', 'That was not snapped in. Mine now.', 'Loose peg. I took the whole {piece}.'],
    good: ['Oh. That fit. That really fit.', 'Good move. Clean seam.', 'Nice. I did not see that part in the box.', 'That clicked. Well built.'],
    win: ['Mate. Every piece locked in. Beautiful build.', 'Checkmate. Fully assembled. No parts left over.', 'Mate. Snap. Complete.'],
    lost: ["Mate. Well assembled. I'd buy that.", 'Checkmate. You built it better. Back to the pile for me.', 'Mate. Missing one part: the win.'],
    resign: ["I'm out of limbs. Resigning. Going back to the pile.", 'I resign. Too many loose pieces.'],
    draw: ["A draw. Nobody's complete. That feels right.", 'A draw. Two unfinished builds.'],
    taken: ['Resigned. Clean break. I like a clean break.', 'You resign. Fine. Half-built games happen.'],
  },

  'dens-crevice': {
    greet: ["Kneel, or just sit. I'm winning either way.", "You've come to my table. Bold. The gold stays on my side.", 'Welcome to the hoard. Touch nothing. Move something.', 'A challenger. How quaint. The cave has seen a thousand.', 'Sit. The treasure is behind me. The board is in front. Choose.'],
    open: ['An opening. Loud, I hope.', 'First moves. I prefer mine with fire.', 'Early. The gold is still mine, the board nearly so.', 'Opening. I come out swinging. Always have.'],
    think: ['I am thinking. The room is warm for a reason.', 'A brilliant move is coming. I can feel it in my chest.', "Don't rush me. I have never needed rushing, only admiring.", 'Thinking. Magnificently.', 'A moment. Greatness takes a moment.', 'Hm. Which piece deserves my attention. All of them.', 'Considering the hoard. I mean the board.', 'Let me look. Dragons look well.', 'Thinking. Do not interrupt a dragon mid-thought. People have been eaten for less.'],
    late: ['Few pieces. The cave grows quiet.', 'Endgame. The gold is restless.', 'Nearly done. The fire burns low. Not out.', "The end. Dragons are good at endings. Usually other people's."],
    ahead: ['Ahead. As is proper.', 'Winning. Naturally. Write it down.', 'The gold approves. So do I.', 'Ahead. Applause is customary, and overdue.'],
    behind: ['Behind. Temporary. Dragons do not lose. We pause.', 'You are ahead. The cave is small. There is nowhere to take it.', 'Losing. Impossible. And yet. Hm.', 'Behind. The fire flickers. Do not look at it.'],
    capture: ['Your {piece}. Added to the hoard.', 'Burn! Another {piece} for the pile.', 'You see? Magnificent.', 'A {piece}, roasted.', 'The {piece} joins my collection. It will not be missed.', 'Taken. The {piece} shines nicely on the pile.', 'Mine. The {piece}, the board, the cave, the gold.'],
    lose: ['A mere {piece}. I have a mountain of them.', "You dare. Fine. I'll melt it down and take it back.", 'That stung. Tell no one.', 'A {piece}, stolen from a dragon. Legends have started that way. Short ones.', 'My {piece}. Gone. The hoard is lighter by one and I notice everything.', 'Hmph. Keep it. It will burn with the rest.', 'You took a {piece}. The cave remembers.'],
    check: ['Check! Feel the heat.', 'Check. Your king looks flammable.', 'Check. Bow, or burn.', 'Check! The fire likes you.', 'Check. Kings have kneeled for less.'],
    checked: ['Check? Cute. Smaller lizards have tried.', 'Check. My king sneezes fire at you.', 'Check on me. Bold. Brief.', 'Check. The cave shakes a little. Only a little.'],
    castled: ['Castled. The king sits on the gold now.', 'Castled. Behind the rook, behind the hoard, behind me.', 'King tucked away. Dragons protect what is theirs.'],
    ucastle: ['Castled. Hiding. I would too.', 'Your king is behind a wall. Walls melt.', 'Castled. Fine. A tower is only kindling with ambition.'],
    promo: ['A new queen, forged from a pawn. The fire does that.', 'Promoted. Gold from lead. Dragon magic, or chess. Same thing.'],
    upromo: ['A new queen on your side. Shiny. I want it.', 'Promoted. Very grand. I collect grand.'],
    blunder: ['You left that there? For me? Oh, you should not have.', 'A free {piece}. Even the hoard did not expect a gift.', 'Careless. The cave punishes careless.', 'You dropped a {piece}. I do not drop things.'],
    good: ['Hm. That was good. Do not do it again.', 'A real move. From a visitor. Rare.', 'Oh. That was clever. I hate clever.', 'Well played. The fire noticed.'],
    win: ['Mate! Naturally. Applause is customary.', 'Checkmate. Another trophy for the hoard.', 'Mate. The cave wins. The cave always wins. Eventually.'],
    lost: ['Mate. Beaten by something smaller, again. Same as every year. Rematch.', 'Checkmate. The hoard is unmoved. I am not.', 'Mate. Fine. Take the board. Leave the gold.'],
    resign: ['I resign. With dignity. Please write down the dignity part.', 'I resign. The fire is out. Do not tell the others.'],
    draw: ['A draw? Beside my own treasure? That barely counts.', 'A draw. Nobody burned. Disappointing.'],
    taken: ['You resign. Good. Say it louder. The hoard likes to hear it.', 'Resigned. Wise. The fire was just getting started.'],
  },

  'heliumdrum': {
    greet: ["Hi. I'm Patch. No relation. Please keep the pointy pieces to yourself.", "Gentle moves, please. I'm already a little flat on one side.", 'Hello. Nothing sharp on you, I hope. Good. Sit.', 'Hi. I float. Try not to make me pop.', "Oh, a game. Lovely. I'll be over here, away from the corners."],
    open: ['Opening. Soft so far. Keep it soft.', 'First moves. Nothing sharp yet. Good.', "Early. I'm holding my breath. Carefully.", 'An opening. Gentle, like a breeze.'],
    think: ['Careful. Very careful. Everything here has an edge.', 'Checking none of my pieces are near a needle.', 'Breathe in. Breathe out. Not too much.', 'Thinking. Quietly. Loud thoughts rattle me.', 'One moment. Drifting toward an idea.', 'Hm. Where is the safest square. There is no safest square.', "Let me float over this a second.", 'Thinking. Trying not to think about pins.', 'Considering. Gently.'],
    late: ['Few pieces left. More room to float.', 'Endgame. Quiet. I like quiet.', 'Nearly over. I am still inflated. That is a win, personally.', 'The end is near. Please, no sudden moves.'],
    ahead: ["Oh. I'm ahead. Don't make a fuss, I'll pop.", 'Winning, gently.', 'Ahead. Floating a little higher.', "I'm up. Nobody touch anything."],
    behind: ["Behind. That's fine. I deflate gracefully.", 'You are ahead. Please be gentle about it.', 'Losing, a little. A slow leak, not a pop.', 'Behind. Drifting lower. Still here.'],
    capture: ['Oh. I took your {piece}. Sorry. I mean, good.', 'Sorry about your {piece}. It was in the way of a breeze.', "That felt fine. I'm going to sit very still now.", 'I bumped your {piece} off. Softly.', 'Your {piece}. Mine. Gently.', 'Oh dear, a {piece}. I did not mean to. I did, a little.', 'Taken. No sharp edges involved.'],
    lose: ["Oh no, my {piece}. That's a leak.", "Pop. Well, a small pop. I'm fine.", 'I felt that one in the seams.', 'My {piece}. Hiss. Still floating.', 'A {piece}, gone. I am a little flatter.', 'Oh. That one hurt. Not a pop though. Not a pop.', 'Lost a {piece}. Deep breath. Not too deep.'],
    check: ['Check. Very gently. Please do not take it personally.', 'Check, softly.', 'Check. Sorry. Sorry. Check.', 'Check. I said it quietly, but it counts.', 'Check. Your king, please, carefully, move.'],
    checked: ['Check. That diagonal looks like a Prick with a needle.', 'Check. Oh. My king. Floating away now.', 'Check. Eek. Okay. Okay.', 'Check on me. Gently moving the king. Gently.'],
    castled: ['Castled. The king is in the softest corner.', 'King tucked in. Away from the pointy bits.', 'Castled. Nice and padded.'],
    ucastle: ['Castled. Good. Safe is good.', 'Your king is cozy. I approve of cozy.', 'A castle. Soft walls, I hope.'],
    promo: ['Oh. A new queen. She floated all the way up.', 'Promoted. Up, up, and queen.'],
    upromo: ['A new queen for you. Please keep her away from me.', 'Promoted. Lovely. Slightly terrifying.'],
    blunder: ['You left that out. I took it. Sorry. Not sorry. Sorry.', 'A free {piece}. Oh. Thank you? Thank you.', 'That was hanging. Like me, but less safely.', 'Oops for you. I floated over and took it.'],
    good: ["Oh. That was sharp. Not sharp sharp. Clever sharp.", 'Good move. I felt the air move.', 'Nice. That gave me a wobble.', 'Well done. Please do fewer of those.'],
    win: ['Mate. Oh. I won. Nobody pop it.', 'Checkmate. Softly. Very softly.', 'Mate. I floated all the way to the end. Nobody touch me.'],
    lost: ["Mate. That's all right. I'm used to deflating.", 'Checkmate. A slow hiss. I am fine. Fine.', 'Mate. Well. Down I go, gently.'],
    resign: ["I resign. I'm losing air and so is the position.", 'I resign. Before something pops.'],
    draw: ['A draw. Nobody got popped. Best result there is.', 'A draw. We both float away. Lovely.'],
    taken: ["Oh. You resigned. That's fine. Nobody got popped.", 'Resigned. Okay. Soft landing.'],
  },

  'washy-washy-ii': {
    greet: ['Sit down. Whatever you lose here, the Wall of Regret remembers.', "Soft hands, hard game. Let's see what you've got under the fluff.", 'Welcome to the back room. First rule: there are no rules. Second rule: I keep score.', 'Sit. Keep your hands on the table. The Wall is watching.', 'A new face. The Wall likes new faces. It has room.'],
    open: ['Opening. Keep your guard up.', 'First moves. Everybody looks tough in the first round.', 'Early. Sizing you up. You are small.', 'Opening bell. Go.'],
    think: ['Hold on. Checking the back room.', 'I know a guy who knows this position.', "Everybody's got a loose thread. Looking for yours.", 'Thinking. Street style. Fast and ugly.', 'One sec. Counting what you owe.', 'Looking for the weak spot. There is always one.', 'Thinking. The Wall has an opinion.', 'Hm. Trade, or hit. Hit, or trade.', 'Give me a second. I keep a ledger for a reason.'],
    late: ['Few pieces. Bare-knuckle time.', 'Endgame. This is where I earn it.', 'Nearly done. The Wall is warming up a spot.', 'Last round. No bell.'],
    ahead: ['Ahead. The ledger says so.', 'Winning. Clean. The Wall approves.', "I'm up. Keep your chin down.", 'Ahead. This is the part where people start regretting.'],
    behind: ['Behind. Street rules: nobody is behind until the ground.', 'You are ahead. I have been here before. I keep score of it.', 'Losing. Fine. It makes the comeback count.', 'Down. Not out. Out is a different wall.'],
    capture: ['Your {piece}. Stitched to the Wall.', 'Business is business. Thanks for the {piece}.', "That's a trade. I forgot to ask you first.", 'One {piece}. Collected. Ledgered.', 'The {piece} went down. Clean hit.', 'Yours. Was. The {piece}.', 'Got the {piece}. Add it to the pile under your name.'],
    lose: ["Fine. Take the {piece}. I'll take what's behind it.", 'You got that one. I keep a ledger.', 'Rough. Not unexpected. Now it is personal.', 'My {piece}. Noted. Everything is noted.', 'Lost a {piece}. The Wall will want yours for it.', 'A hit. Good one. I owe you one back.', 'Ouch. Keep it. It comes back around.'],
    check: ["Check. The door's locked.", 'Check. Your king has no back door.', 'Check. Nowhere to run in the back room.', 'Check. The bouncer says no.', 'Check. Try the window. There is no window.'],
    checked: ["Check. You've been to a fight club before.", 'Check. Good hit. My king blinks.', 'Check. Okay. Okay. Round two.', 'Check on me. Noted. Ledgered. Answered.'],
    castled: ['Castled. The king is in the back room now.', 'King tucked in behind the rook. The door is locked from inside.', 'Castled. Safe house.'],
    ucastle: ['Castled. Hiding in your own back room. Smart.', 'Your king is behind the wall. I know walls.', 'Castled. Fine. Doors open.'],
    promo: ['A new queen. From a pawn that kept its chin down.', 'Promoted. She came up the hard way.'],
    upromo: ['A queen for you. Big hire. The Wall is impressed.', 'Promoted. Good. I like a fair fight.'],
    blunder: ['You left that open. Street rules: I take it.', 'A free {piece}. Even the Wall is embarrassed for you.', 'Loose thread. Pulled it.', 'You dropped your guard. That is a {piece} gone.'],
    good: ['Oh, that was clean. Respect.', 'Nice hit. You have been training.', 'Good move. The back room went quiet.', 'That one landed. Ledgered.'],
    win: ['Mate. Your name goes on the Wall. Spelled right, even.', 'Checkmate. Ledger closed. Wall updated.', 'Mate. Clean. Go wash up.'],
    lost: ["Mate. Clean. They'll stitch my name up there. Ugh.", 'Checkmate. You beat the house. The Wall will remember you fondly.', 'Mate. Good fight. Mine next time.'],
    resign: ['I fold. Even fluff has limits.', 'I resign. The ledger can take one loss.'],
    draw: ['A draw. Nobody stitched. Strange night.', 'A draw. Both still standing. Fine.'],
    taken: ['You fold. Smart. Your name goes on the Wall anyway.', 'Resigned. The Wall takes quitters too.'],
  },

  'yarnia': {
    greet: ["Hello, dear. Sit. I'll knit. You'll lose, gently.", 'Welcome. I remember everything anyone has ever done to me. Shall we?', 'Come in, love. Tea is cold and the game is long.', 'Sit down, dear. Mind the needles. They are for you, later.', 'Hello. I have a long memory and a longer scarf. Begin.'],
    open: ['An opening, dear. Cast on.', 'First rows. Even stitches. Good.', 'Early, love. The pattern has not shown itself yet.', 'Opening. I knit one. You purl, I suppose.'],
    think: ["I'm following the pattern. There is always a loose end.", 'One moment, love. Counting stitches.', 'I can see where it tangles. It tangles here.', 'Thinking, dear. Needles clicking.', 'Hm. A dropped stitch somewhere. Finding it.', 'Let me count the row again.', 'Patience, love. Good things take rows.', 'Thinking. The yarn knows.', 'One moment. I am remembering something you did.'],
    late: ['Few pieces left, dear. Casting off soon.', 'Endgame. The scarf is nearly done. So are you.', 'Nearly there, love. Last rows.', 'The end. I always finish what I start. And what you started.'],
    ahead: ['Ahead, dear. Even stitches.', "I'm winning, love. Don't fuss.", 'Ahead. The pattern is holding.', "I'm up. Tea?"],
    behind: ['Behind, dear. I have unpicked worse.', 'You are ahead. I will remember that too.', 'Losing, love. A dropped row. I will find it.', 'Behind. Patience. Grudges take time.'],
    capture: ['Your {piece}, dear. Into the basket.', 'Snip. Tidy.', 'That one was loose, so I took it.', 'One {piece}, love. Wound up neatly.', 'The {piece}, dear. Thank you.', 'Taken. The {piece} had it coming, in my book. I keep a book.', 'Snip, snip. One {piece}.'],
    lose: ["You took my {piece}. I'll remember which piece.", "That's all right. I'll just find you later.", 'Thank you for the {piece}. I keep a list.', 'My {piece}, dear. Noted. Underlined.', 'A {piece}, gone. I have written down the square.', 'Oh. That one, love. I will be seeing that one again.', 'Fine, dear. The {piece}. The list grows.'],
    check: ['Check, sweetheart. Mind the knot.', "Check. Soft doesn't mean safe.", 'Check, dear. Do sit up.', 'Check, love. The needles are out.', 'Check. Gently, dear. Firmly.'],
    checked: ['Check. Oh, that was petty. I like it.', 'Check, dear. I shall remember who did that.', 'Check. My king is unamused. I am taking notes.', 'Check on me, love. Noted.'],
    castled: ['Castled, dear. The king is wrapped up warm.', 'Castled. Tucked in like a sleeve.', 'King behind the rook. Nice and snug.'],
    ucastle: ['Castled, love. Hiding the king from me. Sensible.', 'Your king is tucked away. I know where the seams are.', 'A castle, dear. Warm, I hope. It will not stay so.'],
    promo: ['A new queen, dear. Knitted from a pawn.', 'Promoted. Lovely work. Mine.'],
    upromo: ['A new queen for you, love. I shall remember her.', 'Promoted. Very nice. I have her measurements.'],
    blunder: ['You left that loose, dear. Loose things get snipped.', 'A free {piece}? Thank you, love. Into the basket.', 'Oh, dear. That was careless. I have a list for careless.', 'A dropped stitch. I picked it up.'],
    good: ['Oh. That was clever, dear. I will remember that too.', 'Good move, love. Even stitches.', 'That was very neat. Hm.', 'Well done, dear. Do not get used to it.'],
    win: ['Mate. All tied off. Lovely work, mine.', 'Checkmate, dear. Cast off. Put the kettle on.', 'Mate, love. The scarf is finished. So are you.'],
    lost: ['Mate. Well. I will stitch that on a pillow so I never forget.', 'Checkmate, dear. I have added you to the list. Top of it.', 'Mate. Lovely. I shall remember every move. Every one.'],
    resign: ['I am unraveling. Resigning, with grace and a long memory.', 'I resign, dear. The pattern was wrong from row three.'],
    draw: ['A draw. I will hold that against both of us.', 'A draw, dear. Nobody tied off. Hm.'],
    taken: ["You resigned, dear. I'll remember how it ended.", 'Resigned, love. The list notes it.'],
  },

  'hungary': {
    greet: ["Pull up a chair. I'm fresh right now, so don't wait too long.", 'Good value, this game. Nobody gets eaten. Mostly.', "Sit. I'm best before move twenty-four. Clock's ticking.", 'Hello. Fresh out of the oven. Let us go before I cool.', "Welcome. I'm a snack. The game is the meal."],
    open: ['Opening. Fresh moves. Crisp.', 'First bites. Mine are the sharpest.', 'Early. Everything is still warm.', 'An opening. Good crust on it.'],
    think: ['Letting it simmer. Good moves take time. Mine do, anyway.', 'Checking the shelf life of my plan.', 'Comparing ingredients. Nothing here is the main course. Yet.', 'Thinking. Still fresh. Still sharp.', 'One moment. Tasting the position.', 'Hm. This needs salt.', 'Stirring. The move is nearly done.', 'Thinking. Trying not to crumble.', 'Let it cool. Then I bite.'],
    late: ['Few pieces. The plate is nearly clean.', 'Endgame. Past my date, maybe. Still here.', 'Nearly done. Dessert next.', 'The end. Everything spoils. Finish strong.'],
    ahead: ['Ahead. Fresh and winning.', 'Winning. Good value for a snack.', "I'm up. Still crisp.", 'Ahead. Do not let me go stale on it.'],
    behind: ['Behind. Getting a little stale.', 'You are ahead. I am a bit crumbly about it.', 'Losing. Past my date, maybe.', 'Behind. Still edible. Still fighting.'],
    capture: ['Your {piece} is on the plate. Sorry.', 'Tasty. Not great. But tasty.', 'Food fight rules. Leave ammunition lying around, I take it.', 'One {piece}, eaten.', 'The {piece}. Crunch.', 'Your {piece}, served.', 'Took the {piece}. Needed a bite.'],
    lose: ['Ouch. That {piece} was meant for dessert.', "You took my {piece}. I'm a snack. We bounce back.", 'That one hurt. I am just a little crumby about it.', 'My {piece}. Off the plate.', 'A {piece}, gone. Still fresh. Mostly.', 'You bit first. Fair.', 'Lost a {piece}. Crumbs everywhere.'],
    check: ["Check. Please don't squish the king.", 'Check. Hot and fresh.', 'Check. Served warm.', 'Check. Mind the crust.', 'Check. That one had bite.'],
    checked: ['Check. Sharp. I felt that one in my crust.', 'Check. My king wobbles like jelly.', 'Check. Okay. Still fresh. Moving.', 'Check on me. Spicy.'],
    castled: ['Castled. The king is in the breadbox.', 'Castled. Wrapped up to stay fresh.', 'King tucked in. Airtight.'],
    ucastle: ['Castled. Keeping the king fresh. Smart.', 'Your king is in the pantry now.', 'A castle. Good crust on that.'],
    promo: ['A new queen. Baked from a pawn.', 'Promoted. Risen nicely.'],
    upromo: ['A queen for you. Fresh batch.', 'Promoted. Nice rise on that one.'],
    blunder: ['You left that out. Things left out get eaten.', 'A free {piece}. Snack time.', 'Uncovered. I covered it. With my mouth.', 'That was careless. Delicious, though.'],
    good: ['Oh. That was sharp. Good bite.', 'Nice. That one had flavor.', 'Good move. I felt that in my filling.', 'Well cooked. Hm.'],
    win: ['Mate. I got to the end before I spoiled. Good day.', 'Checkmate. Fresh to the last bite.', 'Mate. Dinner is done. I was the dinner and the winner.'],
    lost: ["Mate. I lasted longer than I expected. That's a win for a snack.", 'Checkmate. I went stale at the wrong moment.', 'Mate. You ate well.'],
    resign: ["I'm past my date. Resigning, before it gets sad.", 'I resign. Nobody wants a stale game.'],
    draw: ['A draw. We both made it to dessert.', 'A draw. Split the last bite.'],
    taken: ["You resigned. I hadn't even spoiled yet. Good value.", 'Resigned. Fine. More for me.'],
  },

  'guffaw-7': {
    greet: ["Good evening. Tough crowd tonight. It's just you. Tougher.", "Don't laugh. Laugh once and you're the act.", 'Welcome to the show. One night only, every night.', 'Sit down. No heckling. That is my job.', "Is this thing on? It's a chessboard. Of course it isn't."],
    open: ['Opening bit. The warm-up. Nobody laughs at the warm-up.', 'First moves. Setting up the joke.', 'Early. The room is still deciding about you.', 'An opening. Classic material. Mine.'],
    think: ["Folks, I'm thinking. The act is thinking.", "So there's this knight. And I don't have a punchline. Hang on.", "Tough room. I haven't moved and you're already staring.", 'Thinking. Give me a second. Timing is everything.', 'Hold for thought. Hold. Hold.', "Okay, here's the bit. No, wait. Here's the bit.", 'Thinking. The silence is part of the act.', 'One second. Writing this move on my hand.', 'Working on it. Comedy is hard. Chess is harder. Both at once is a career.'],
    late: ['Endgame. The closer. Big finish.', 'Few pieces. Few jokes. Make them count.', 'Nearly the end. Stick around for the encore. There is no encore.', 'Last bit of the night. Tough room to the end.'],
    ahead: ["I'm ahead. The room is finally with me.", 'Winning. Somebody laughed. I think it was me.', 'Ahead. This is the good part of the set.', "I'm up. Tell your friends. They won't come."],
    behind: ["Behind. I'm bombing. Beautifully.", 'You are ahead. The room is yours. Enjoy the silence.', 'Losing. This is where I usually do crowd work. Hi.', 'Behind. Tough room. Tough board. Tough me.'],
    capture: ["Took your {piece}. Tell your friends. No, don't. They'll want it back.", "Great {piece}. Wonderful. It's in my act now.", "That's the setup. The punchline is your face.", 'One {piece}. Thank you, you have been a lovely {piece}.', 'The {piece} is gone. Give it up for the {piece}.', 'Got your {piece}. And that is the bit.', 'Your {piece}. Mine. Ba-dum.'],
    lose: ["Wow. You took my {piece}. That's a tough room.", 'Hey, that was my best bit. Fine.', "You got the {piece}. I'll get the applause.", 'My {piece}. Gone. Like my hopes for this set.', 'Lost a {piece}. Heckled by the board.', 'Okay. Okay. The {piece} bombed. Moving on.', 'That hurt. Put it in the special.'],
    check: ['Check. Hold for laughter.', 'Check. Wait for it.', 'Check. That is the callback.', 'Check. Timing.', 'Check. And the crowd goes mild.'],
    checked: ["Check. Predictable. Third time I've seen that tonight.", 'Check. Heckler in the front row.', 'Check. Fine. Tough room.', 'Check on me. Everybody is a comedian.'],
    castled: ['Castled. The king is backstage now.', 'Castled. Exit stage left, behind the rook.', 'King in the wings. Safe from the room.'],
    ucastle: ['Castled. Leaving before the bad part. Smart.', 'Your king is backstage. I have a key.', 'Castled. Okay. Hiding from the act.'],
    promo: ['A new queen. From a pawn. Thats the arc.', 'Promoted. Headliner now.'],
    upromo: ['A queen for you. Big night. Tough room though.', 'Promoted. Okay. Okay. Nice.'],
    blunder: ['Oh, you blew that one. And the whole room saw.', 'A free {piece}. That is the funniest thing you have done all night.', 'You dropped it. The room laughed. Finally.', 'Oof. That is going in the act.'],
    good: ['Oh. Good move. The room went quiet, in a good way.', 'Nice. Somebody wrote that one down.', 'That was sharp. Heckled by a pro.', 'Good move. I hate it. Respect.'],
    win: ["Mate. Thank you, you've been wonderful. Drive safe.", 'Checkmate. That is the show. Tip your knights.', 'Mate. Big finish. Nobody laughed. Still a finish.'],
    lost: ["Mate. I bombed. Beautifully. I'll take it.", 'Checkmate. The room belongs to you. Do a set.', 'Mate. Tough crowd. Tougher opponent.'],
    resign: ["I resign. Nobody's laughing. That's a bomb. See you at the next show.", 'I resign. Walking off before the hook.'],
    draw: ["A draw. Nobody laughed and nobody won. That's Guffaw-7.", 'A draw. Split the bill. Split the room.'],
    taken: ["You resigned? Tough room. That's the shortest act I've seen.", 'Resigned. Leaving mid-set. Rude. Smart.'],
  },

  'spee-ider-grove': {
    greet: ["Come in, come in. Mind the threads. They're mostly decoration.", "The web's fast today. About three minutes. Let's not waste them.", 'Sit. Do not touch the web. You are already touching the web.', 'Welcome. Everything in here is connected. To me. Begin.', 'Hello. Fast game? The web is humming.'],
    open: ['Opening. The first thread goes out.', 'Early. Spinning. Quietly.', 'First moves. Laying the web.', 'An opening. Do not look at the corners.'],
    think: ['Tracking connections. Everything here is connected. To me.', "Moving fast. Don't blink.", "Setting something up. Don't look at the left side.", 'Thinking. Eight legs, eight ideas.', 'One second. The web is deciding.', 'Spinning. Plot twist incoming.', 'Hm. Which thread to pull.', 'Thinking fast. The web does not wait.', 'Hold still. The trap is nearly set.'],
    late: ['Few pieces. The web is tight now.', 'Endgame. Everything is connected. Watch.', 'Nearly done. The last thread goes here.', 'The end. The web always finishes.'],
    ahead: ['Ahead. The web holds.', 'Winning. Everything is where I spun it.', "I'm up. Plot twist: there is no twist.", 'Ahead. Dinner is nearly served.'],
    behind: ['Behind. A thread broke. I have more.', 'You are ahead. The web is being re-spun.', 'Losing. Plot twist incoming. Maybe.', 'Behind. Fast fix. Faster.'],
    capture: ['Caught your {piece}. It was already stuck.', 'Dinner for one. Sorry. Your {piece} looked so good.', 'Wrapped and tidy. Thank you for the {piece}.', 'One {piece}, in the web.', 'The {piece} walked right in.', 'Got the {piece}. Plot twist.', 'Your {piece}. Mine. Wrapped.'],
    lose: ['You cut a thread. Cute.', 'You caught my {piece}. Plot twist: I wanted you to.', "Okay, that's a hole. I have more web.", 'My {piece}. A thread snapped. Spinning another.', 'Lost a {piece}. The web adjusts.', 'Hm. A {piece} gone. Noted. Connected.', 'That cut. Fine. Eight legs left.'],
    check: ['Check! Plot twist.', 'Check. The web is humming.', 'Check. Caught in a thread.', 'Check. Fast, was it not.', 'Check. Do not struggle. It tightens.'],
    checked: ['Check. You found a thread. Careful where you pull.', 'Check. My king skitters. Fine.', 'Check on me. Fast. Noted.', 'Check. Hm. A thread I did not spin.'],
    castled: ['Castled. The king is in the center of the web.', 'Castled. Wrapped up safe.', 'King tucked in. Threads all around.'],
    ucastle: ['Castled. Hiding the king. The web finds everything.', 'Your king is in a corner. Corners are mine.', 'A castle. Nice. Threads go through walls.'],
    promo: ['A new queen. Spun from a pawn.', 'Promoted. Eight legs better.'],
    upromo: ['A queen for you. She is already in the web, she does not know yet.', 'Promoted. Fast. I like fast.'],
    blunder: ['You left that hanging. Hanging things go in the web.', 'A free {piece}. Walked right in.', 'Careless. The web loves careless.', 'You dropped a {piece}. Caught it.'],
    good: ['Oh. That was fast. Faster than me.', 'Good move. A thread I did not see.', 'Nice. Plot twist, and not mine.', 'Sharp. The web shivered.'],
    win: ['Mate. Dinner is served. For one.', 'Checkmate. The web closes.', 'Mate. Plot twist: it was always going to end here.'],
    lost: ["Mate. You pulled the right thread. I'll think about it for about three minutes.", 'Checkmate. The web came apart. Respect.', 'Mate. Fast and clean. I should know.'],
    resign: ["I'm letting go. Clean. That's the whole philosophy.", 'I resign. The web is down. Spinning a new one.'],
    draw: ["A draw. No twist. I'm disappointed in both of us.", 'A draw. Two webs, no dinner.'],
    taken: ['You let go. Clean. I have to respect that, a little.', 'Resigned. Out of the web. For now.'],
  },
};
