/* IN PIECES: what each being says while you put its planet back together. Same voices as the board and the maze.
   greet  you open its puzzle     start  your first swap     lock   a piece clicks into place (said once or twice a game)
   hint   you press Hint          solve  you press Solve (it finishes it; that does not count)
   slow   ninety seconds in       win    you finish it       locked you tap a planet that is not open yet    next   you pick the next planet */

export const PUZZLE_LINES = {
  'planet-zee': {
    greet: ['My planet, in pieces. It was in pieces before. Nobody minded.', 'Put it back together. Take your time. The pieces have.', 'Welcome. Twenty-five pieces, or nine. All of them patient.'],
    start: ['A swap. The first of many, I expect.', 'Moving pieces. The pieces have waited for this.', 'There. One swap. The queue begins.'],
    lock: ['One in place. It will stay. Everything here stays.', 'That one fits. File it.', 'Locked. One piece done waiting.'],
    hint: ['Numbers. A hint. Noted on your file.', 'The numbers, for five seconds. That is a long time here. It is not.', 'Fine. The order, shown. Briefly.'],
    solve: ['I will finish it. It does not count. Nothing here counts.', 'Solved, by me. The record stays blank.', 'There. Watch it assemble. Feel nothing.'],
    slow: ['Ninety seconds. On Planet Zee that is a blink.', 'Still at it. Good. Most never finish anything here.', 'Take your time. I have taken all of mine.'],
    win: ['Back together. Stamped, dated, filed.', 'Whole again. It happens, rarely. Mark the date.', 'Done. The planet thanks you, slowly.'],
    locked: ['Not yet. Finish mine first.', 'That one is closed. This one is open. Patience.', 'One planet at a time. That is the line.'],
    next: ['Go on. The next one has more pieces, or seems to.', 'Off you go. Tell the next being nothing.'],
  },
  'yaaarghs-revenge': {
    greet: ['My planet, in pieces. I copied the pieces from a better planet.', 'Put it back. I would, but I copy, I do not build.', 'Welcome aboard. The picture is stolen. The pieces are yours to sort.'],
    start: ['A swap. I will be copying that.', 'Moving pieces. Mind, I am watching the order.', 'First swap. Mine was the same, on somebody else\'s puzzle.'],
    lock: ['That one fits. I will claim I placed it.', 'Locked. Good. Copied.', 'One in. I had nothing to do with it. I will say I did.'],
    hint: ['Numbers? That is cheatin. I approve.', 'The order, shown. I copied it from the answer key.', 'Fine. Five seconds of numbers.'],
    solve: ['I will finish it. Ye owe me a ship.', 'Solved. By me. The credit stays aboard.', 'There. Done. Memorize it, like I did.'],
    slow: ['Ninety seconds. I would have copied a finished one by now.', 'Still at it? Follow someone. That is my whole method.', 'Lost in the pieces. Happens to the best thieves.'],
    win: ['Back together. I will be stealin that order.', 'Whole. Copied it down. Thanks.', 'Done. Now I know the way too.'],
    locked: ['That one is locked. Mine first.', 'Not yet. Finish robbin me before ye rob them.', 'Closed. This one is open. Get on with it.'],
    next: ['Go on. The next one is harder. I copied it myself.', 'Off ye go. Take the order with ye, I did.'],
  },
  'oogh-iv': {
    greet: ['Zug planet broken. You fix. Zug watch.', 'Pieces everywhere. Zug not do this. Probably.', 'Welcome. Put rock back. Rock is planet.'],
    start: ['You move piece. Good. Zug cheer.', 'Swap. Zug saw. Zug proud.', 'First swap. Zug clap.'],
    lock: ['That one stick! Good!', 'Piece fit. Zug happy.', 'Locked. Zug not know word. Zug like it.'],
    hint: ['Numbers! Zug can count to some of them.', 'Hint. Zug point. There. And there.', 'Zug help. Shh.'],
    solve: ['Zug fix whole thing. Zug smart today. No prize.', 'Zug solve. You watch. Zug tired after.', 'There. All fixed. Zug nap.'],
    slow: ['Long time. Zug find snack. Zug back.', 'Still broken? Zug wait. Zug good at wait.', 'You lost? Zug lost too. Zug not say.'],
    win: ['Fixed! Planet fixed! Zug yell!', 'You put rock back. Zug never could. Zug happy for you.', 'Whole! Zug dance!'],
    locked: ['No. That one shut. Zug planet first.', 'Locked. Fix Zug first. Zug important.', 'Not yet. Zug. Then that one.'],
    next: ['Go next. Next being less nice. Zug warn.', 'Bye. Zug wave. Zug keep waving.'],
  },
  'prearth': {
    greet: ['My planet, in pieces. The rock did that. Put it back before the next one.', 'Welcome. Twenty-five pieces, three minutes, one sky falling.', 'Pieces. Move. The beat is fast.'],
    start: ['A swap. Keep the beat.', 'Moving. Faster. The sky is not waiting.', 'First swap. Good. Do a hundred more.'],
    lock: ['Click. One in. Loud.', 'That one fits. The band noticed.', 'Locked. Keep dancing.'],
    hint: ['Numbers. The sky gives hints too. Louder ones.', 'Five seconds of order. Then chaos again.', 'Fine. The numbers. Follow them like a tail.'],
    solve: ['I will finish it. Does not count. Nothing counts when the sky falls.', 'Solved. By me. No trophy.', 'There. Whole. Fast, like everything here.'],
    slow: ['Ninety seconds. The rock is closer than you are to done.', 'Still at it. Dance while you work.', 'Lost in the pieces. Fine. Turn the music up.'],
    win: ['Whole! Before the rock. Barely.', 'Back together. The sky noticed. It is still coming.', 'Done. Loud. The way we like it.'],
    locked: ['Not yet. Mine first.', 'That one is shut. The rock will open it later.', 'Locked. Finish here. Then there.'],
    next: ['Go. The next one is colder. Keep the beat anyway.', 'Off you go. Tell them Prearth sends its rock.'],
  },
  'that-other-planet': {
    greet: ['Unit 7 planet. Disassembled for transport. Reassembly is billable.', 'Welcome. The pieces are numbered internally. The numbers are available for a fee.', 'Proceed. Every swap is logged.'],
    start: ['Swap logged. Suboptimal, but logged.', 'First move. Timer started. Billing started.', 'Proceeding. Please keep to the grid.'],
    lock: ['Piece seated. Confirmed. Fee unchanged.', 'Locked. One unit of progress.', 'Correct placement. Noted.'],
    hint: ['Numbers provided. Consulting rate applies.', 'A hint. Five seconds. Itemized.', 'Hint delivered. Efficiency, purchased.'],
    solve: ['Full reassembly by Unit 7. This does not count as yours. It counts as my fee.', 'Solved. Credit: Unit 7.', 'Observe the optimal order. Pay later.'],
    slow: ['Ninety seconds. Your rate is unchanged.', 'Still in progress. The invoice grows with you.', 'Inefficient. Noted. Billed.'],
    win: ['Reassembly confirmed. Your total is on the back.', 'Complete. Time and moves logged. Invoice issued.', 'Whole. Acceptable. Payment terms apply.'],
    locked: ['That planet is not yet available. Complete this one first.', 'Locked. Sequential access only.', 'Not open. This one is. Proceed.'],
    next: ['Proceed to the next planet. Rates increase.', 'Go. The next consultant is less reasonable.'],
  },
  'figuria': {
    greet: ['My planet, in pieces. Snap-fit. Most of them.', 'Welcome. Twenty-five parts, one picture, no instructions.', 'Come in. Mind the small parts.'],
    start: ['A swap. Good articulation.', 'First piece moved. Joints working.', 'There you go. Snap, snap.'],
    lock: ['Click. That one fit.', 'Snap. Locked.', 'Good seam. One in.'],
    hint: ['Numbers. Like the instructions, but honest.', 'A hint. I would have dug through the pile for that.', 'Fine. Five seconds of order.'],
    solve: ['I will finish it. Does not count. A kit built by someone else is not yours.', 'Solved. By me. Put it on the shelf.', 'There. Every part in place. Watch.'],
    slow: ['Ninety seconds. Missing a part, I think.', 'Still building. The pile is deep.', 'Lost. Something is always missing.'],
    win: ['Whole. Clean build.', 'Back together. Every piece fit.', 'Done. Snap. Complete.'],
    locked: ['Not yet. Finish this build first.', 'That one is still in the box.', 'Locked. One kit at a time.'],
    next: ['Go on. The next one has more parts.', 'Off you go. Take a spare.'],
  },
  'dens-crevice': {
    greet: ['My cave, in pieces. Someone will pay for that. Put it back.', 'Welcome. The picture is of my hoard. Do not get ideas.', 'Pieces. Assemble them. Magnificently, if you can.'],
    start: ['A swap. Brave. Briefly.', 'Moving pieces of my cave. Careful.', 'First swap. I am watching from above.'],
    lock: ['That one fits. The fire approves.', 'Locked. The hoard is one piece safer.', 'Click. Good. Continue.'],
    hint: ['Numbers. The dragon gives nothing free. This is nearly nothing.', 'A hint, burned into the pieces. Five seconds.', 'Fine. The order. The fire drew it.'],
    solve: ['I will finish it. Does not count. Dragons do not share.', 'Solved. By me. Applause is customary.', 'There. Whole. Magnificent, is it not.'],
    slow: ['Ninety seconds. The cave keeps what the cave likes.', 'Still at it. Warmer yet?', 'Lost in my cave. Many are.'],
    win: ['Whole. The hoard is restored. Go, before I change my mind.', 'Back together. The fire remembers your name.', 'Done. Hm. The hoard is unmoved. I am, a little.'],
    locked: ['Not yet. Mine first.', 'That one is sealed. This one is open.', 'Locked. The gold says so.'],
    next: ['Go. The next cave is colder and the host is softer.', 'Off you go. Leave the gold.'],
  },
  'heliumdrum': {
    greet: ['My planet, in pieces. Softly, please, putting it back.', 'Welcome. Twenty-five pieces. None of them sharp. I checked.', 'Hi. Please do not bump the pieces. Or me.'],
    start: ['A swap. Gently. Good.', 'First piece moved. Okay. Okay.', 'There you go. Float them into place.'],
    lock: ['Oh. That one fits. Lovely.', 'Click. Softly. Locked.', 'One in. No pops. Good.'],
    hint: ['Numbers. Softly. Five seconds.', 'A hint. Please do not tell the corners.', 'Fine. The order. It looks sharp but it is not.'],
    solve: ['I will finish it. It does not count. I would feel bad counting it.', 'Solved. By me. Quietly.', 'There. Whole. No sharp turns. Well, some.'],
    slow: ['Ninety seconds. Breathe. Not too much.', 'Still at it. Drifting counts.', 'Lost. Gently lost. Keep going.'],
    win: ['Whole! Oh. Nobody pop anything.', 'Back together. Softly. Lovely.', 'Done. I am so relieved.'],
    locked: ['Not yet. Finish mine first. Gently.', 'That one is closed. This one is soft. Stay.', 'Locked. Sorry. Keep going here.'],
    next: ['Go on. The next one has edges. Be careful.', 'Off you float. Mind the needles.'],
  },
  'washy-washy-ii': {
    greet: ['My planet, in pieces. Back-room rules. Put it together.', 'Welcome. The Wall is watching you sort.', 'Pieces. Chin down. Go.'],
    start: ['A swap. Keep your guard up.', 'First move. Ledgered.', 'There you go. Street style.'],
    lock: ['That one landed. Locked.', 'Click. Clean hit.', 'One in. The Wall approves.'],
    hint: ['Numbers. The Wall remembers who asked.', 'A hint. Five seconds. The rest costs you.', 'Fine. The order. Do not get used to help.'],
    solve: ['I will finish it. Does not count. The Wall knows.', 'Solved. By me. Your name goes nowhere.', 'There. Whole. Watch and learn.'],
    slow: ['Ninety seconds. The Wall is warming up a spot.', 'Still at it. Comfy back room, is it.', 'Lost in the pieces. Happens to the tough ones too.'],
    win: ['Whole. Clean. The Wall spells your name right.', 'Back together. Ledgered.', 'Done. Respect.'],
    locked: ['Not yet. Mine first.', 'That one is locked. This one is open.', 'Locked. One room at a time.'],
    next: ['Go on. The next room is meaner.', 'Off you go. The Wall has room for more.'],
  },
  'yarnia': {
    greet: ['My planet, in pieces, dear. Like a pattern cut up. Put it right.', 'Come in, love. Twenty-five squares. Knit them back.', 'Welcome. Mind the loose ends, dear.'],
    start: ['A swap, dear. Good. Even stitches.', 'First row, love. Lovely.', 'There you go. Follow the pattern.'],
    lock: ['That one fits, dear. Tidy.', 'Click. One square in. Lovely.', 'Locked, love. Neat.'],
    hint: ['Numbers, dear. I will remember you asked.', 'A hint, love. Five seconds of pattern.', 'Fine. The order. Mind it does not tangle.'],
    solve: ['I will finish it, dear. It does not count. Finished by me is not finished by you.', 'Solved, love. By me. I keep the pattern.', 'There. Whole. Tidy, is it not.'],
    slow: ['Ninety seconds, dear. Patience. I have plenty.', 'Still at it, love. The wool is warm at least.', 'Lost in the squares. Keep pulling.'],
    win: ['Whole, dear. Cast off. Lovely.', 'Back together, love. I shall remember how.', 'Done. Well done, dear.'],
    locked: ['Not yet, dear. Finish mine first.', 'That one is tied off. This one is open.', 'Locked, love. Patience.'],
    next: ['Go on, dear. The next one is knitted tighter.', 'Off you go, love. I have your measurements.'],
  },
  'hungary': {
    greet: ['My planet, in pieces. Like a cookie somebody sat on. Put it back before it goes stale.', 'Welcome. Twenty-five bites. Reassemble.', 'Fresh pieces. Move before they cool.'],
    start: ['A swap. Good. Before it cools.', 'First bite. Keep going.', 'There you go. Crisp.'],
    lock: ['That one fits. Crunch.', 'Click. Locked. Still fresh.', 'One in. Good crust.'],
    hint: ['Numbers. Half the recipe.', 'A hint. Five seconds. Follow the crumbs.', 'Fine. The order. Served warm.'],
    solve: ['I will finish it. Does not count. A meal somebody else ate is not yours.', 'Solved. By me. Plate cleared.', 'There. Whole. Served.'],
    slow: ['Ninety seconds. Getting stale yet?', 'Still at it. The oven is off. Hurry.', 'Lost in the crumbs. Everything spoils. Finish anyway.'],
    win: ['Whole. Fresh to the end.', 'Back together. Dessert is yours.', 'Done before it spoiled. Good value.'],
    locked: ['Not yet. Clear this plate first.', 'That one is in the oven. This one is served.', 'Locked. One course at a time.'],
    next: ['Go on. The next one is spicier.', 'Off you go. Take a crumb.'],
  },
  'guffaw-7': {
    greet: ['My planet, in pieces. Tough room. Put it together, no laughing.', 'Welcome. Twenty-five pieces. That is the setup. You are the punchline.', 'Pieces. Timing. Go.'],
    start: ['A swap. The warm-up. Nobody claps.', 'First move. Hold for laughter. Nothing. Keep going.', 'There you go. Timing.'],
    lock: ['That one landed. Finally, applause. Mine.', 'Click. A laugh. Small one.', 'Locked. That is the callback.'],
    hint: ['Numbers. The heckler in the booth helps you. Tough room.', 'A hint. Five seconds. The punchline is still yours.', 'Fine. The order. That is the bit.'],
    solve: ['I will finish it. Does not count. Somebody else did the bit.', 'Solved. By me. Tip your knights.', 'There. Whole. Big finish. Nobody laughed.'],
    slow: ['Ninety seconds. That is a long pause even for me.', 'Still at it. Bombing. Beautifully.', 'Lost in the pieces. Crowd work time. Hi.'],
    win: ['Whole. Thank you, you have been wonderful. Drive safe.', 'Back together. The room went quiet, in a good way.', 'Done. That is the show.'],
    locked: ['Not yet. Finish my set first.', 'That one is dark tonight. This one is open mic.', 'Locked. One act at a time.'],
    next: ['Go on. The next room is tougher. They all are.', 'Off you go. Tell them Guffaw-7 sent you.'],
  },
  'spee-ider-grove': {
    greet: ['My planet, in pieces. Everything connects. Find how.', 'Welcome. Twenty-five pieces, one web. Mind the threads.', 'Come in, come in. The picture moves. Plot twist.'],
    start: ['A swap. Fast. Good.', 'First move. The web felt it.', 'There you go. Do not look at the corners.'],
    lock: ['That one fits. A thread, tied.', 'Click. Connected.', 'Locked. The web tightens.'],
    hint: ['Numbers. Five seconds of web.', 'A hint. The red thread, in numbers.', 'Fine. The order. Fast.'],
    solve: ['I will finish it. Does not count. The web knows who moved.', 'Solved. By me. Wrapped and tidy.', 'There. Whole. Spun in three minutes.'],
    slow: ['Ninety seconds. The web is humming.', 'Still at it. The threads tighten, you know.', 'Lost in the pieces. Do not struggle. Or do.'],
    win: ['Whole. You tied the right threads.', 'Back together. The web shivered.', 'Done. Plot twist: I let you. No I did not.'],
    locked: ['Not yet. Out of my web first.', 'That one is wrapped. This one is open.', 'Locked. One web at a time.'],
    next: ['That was the last one. All thirteen, whole. The beings would like a word over the board.', 'No next. You are at the end of the route. Sit down and play me at chess.'],
  },
};
